"""P3-3-W2: 53 legacy workflow templates (image/video/audio/annotation/cleaning/scoring/dataset/export/ops).

This file holds the original template list extracted from the pre-W2
``templates.py`` module. The new ``templates/__init__.py`` registry
re-exports them alongside the 25 business templates added in P3-6-W2.
"""
from __future__ import annotations

from typing import Any, Dict, List

from ._helpers import _n


_BASE_TEMPLATES: List[Dict[str, Any]] = [
    # ============ IMAGE GENERATION (10) ============
    {"id": "tpl-img-001", "category": "image",
     "name": "Text-to-Image Basic", "tags": ["text2img", "stable-diffusion"],
     "description": "Single-step text-to-image generation.",
     "nodes": [_n("gen", "text-to-image", "generation")]},
    {"id": "tpl-img-002", "category": "image",
     "name": "Text-to-Image + Cleanup", "tags": ["text2img", "clean"],
     "description": "Generate, then dedup & dedupe-hash.",
     "nodes": [_n("gen", "generate", "generation"),
               _n("cln", "cleanup", "cleaning", "gen")]},
    {"id": "tpl-img-003", "category": "image",
     "name": "Text-to-Image + Aesthetic Score",
     "tags": ["text2img", "aesthetic"],
     "description": "Generate images, score with aesthetic model.",
     "nodes": [_n("gen", "generate", "generation"),
               _n("sc", "aesthetic_score", "scoring", "gen")]},
    {"id": "tpl-img-004", "category": "image",
     "name": "Image-to-Image Edit", "tags": ["img2img", "edit"],
     "description": "Apply img2img transform with strength ramp.",
     "nodes": [_n("ed", "img2img-edit", "generation")]},
    {"id": "tpl-img-005", "category": "image",
     "name": "ControlNet Pose-to-Image",
     "tags": ["controlnet", "pose"],
     "description": "Pose-conditioned image generation.",
     "nodes": [_n("pose", "extract_pose", "preprocessing"),
               _n("gen", "controlnet_generate", "generation", "pose")]},
    {"id": "tpl-img-006", "category": "image",
     "name": "Inpainting", "tags": ["inpaint", "mask"],
     "description": "Mask-driven inpainting pipeline.",
     "nodes": [_n("mk", "mask_prep", "preprocessing"),
               _n("ip", "inpaint", "generation", "mk")]},
    {"id": "tpl-img-007", "category": "image",
     "name": "Outpainting", "tags": ["outpaint", "extend"],
     "description": "Extend image beyond borders.",
     "nodes": [_n("op", "outpaint", "generation")]},
    {"id": "tpl-img-008", "category": "image",
     "name": "Upscale x4", "tags": ["upscale", "esrgan"],
     "description": "Real-ESRGAN upscale chain.",
     "nodes": [_n("up", "upscale_4x", "enhancement", retry_max=1)]},
    {"id": "tpl-img-009", "category": "image",
     "name": "Face Restore", "tags": ["face", "restore", "gfpgan"],
     "description": "Detect + restore faces.",
     "nodes": [_n("fd", "face_detect", "preprocessing"),
               _n("fr", "face_restore", "enhancement", "fd")]},
    {"id": "tpl-img-010", "category": "image",
     "name": "Watermark Embed",
     "tags": ["watermark", "copyright"],
     "description": "Apply invisible watermark to outputs.",
     "nodes": [_n("wm", "embed_watermark", "postprocessing")]},

    # ============ VIDEO GENERATION (8) ============
    {"id": "tpl-vid-001", "category": "video",
     "name": "Text-to-Video Short", "tags": ["t2v", "short"],
     "description": "5-second text-to-video generation.",
     "nodes": [_n("t2v", "text-to-video", "video_generation")]},
    {"id": "tpl-vid-002", "category": "video",
     "name": "Image-to-Video Animate",
     "tags": ["i2v", "animate"],
     "description": "Animate a still image into a short clip.",
     "nodes": [_n("i2v", "image-to-video", "video_generation")]},
    {"id": "tpl-vid-003", "category": "video",
     "name": "Frame Interpolation", "tags": ["rife", "interp"],
     "description": "Interpolate between frames for smoothness.",
     "nodes": [_n("ri", "rife_interp", "video_enhancement")]},
    {"id": "tpl-vid-004", "category": "video",
     "name": "Video Upscale + Restore",
     "tags": ["video", "upscale"],
     "description": "Upscale video frames + face restore.",
     "nodes": [_n("vu", "video_upscale", "video_enhancement", retry_max=1),
               _n("fr", "face_restore", "enhancement", "vu")]},
    {"id": "tpl-vid-005", "category": "video",
     "name": "Storyboard to Video",
     "tags": ["storyboard", "multi-shot"],
     "description": "Compose multi-shot video from storyboard.",
     "nodes": [_n("sb", "storyboard", "preprocessing"),
               _n("vs", "shot_generation", "video_generation", "sb"),
               _n("vc", "compose", "video_compose", "vs")]},
    {"id": "tpl-vid-006", "category": "video",
     "name": "Short-Drama Pipeline",
     "tags": ["drama", "series"],
     "description": "Generate a short-drama episode end-to-end.",
     "nodes": [_n("sc", "script", "scripting"),
               _n("sb", "storyboard", "preprocessing", "sc"),
               _n("vs", "shot", "video_generation", "sb"),
               _n("ed", "edit", "video_compose", "vs"),
               _n("au", "audio_mix", "audio", "ed")]},
    {"id": "tpl-vid-007", "category": "video",
     "name": "Lip-Sync Video", "tags": ["lipsync", "wav2lip"],
     "description": "Apply lip-sync to existing video.",
     "nodes": [_n("au", "extract_audio", "audio"),
               _n("ls", "lip_sync", "video_generation", "au")]},
    {"id": "tpl-vid-008", "category": "video",
     "name": "Video Watermark + Caption",
     "tags": ["video", "watermark"],
     "description": "Add watermark + burned-in captions.",
     "nodes": [_n("wm", "watermark", "postprocessing"),
               _n("cp", "captions", "postprocessing")]},

    # ============ AUDIO (5) ============
    {"id": "tpl-aud-001", "category": "audio",
     "name": "Text-to-Speech", "tags": ["tts"],
     "description": "Synthesize speech from text.",
     "nodes": [_n("tts", "tts", "tts")]},
    {"id": "tpl-aud-002", "category": "audio",
     "name": "Voice Clone", "tags": ["tts", "clone"],
     "description": "Clone a voice from a sample.",
     "nodes": [_n("pr", "preprocess", "audio"),
               _n("cl", "clone", "tts", "pr")]},
    {"id": "tpl-aud-003", "category": "audio",
     "name": "Music Generation", "tags": ["music", "bgm"],
     "description": "Generate background music from prompt.",
     "nodes": [_n("mg", "music_generate", "music_generation")]},
    {"id": "tpl-aud-004", "category": "audio",
     "name": "Audio Denoise", "tags": ["denoise"],
     "description": "Denoise + dereverb audio.",
     "nodes": [_n("dn", "denoise", "audio_enhancement")]},
    {"id": "tpl-aud-005", "category": "audio",
     "name": "Sound Effects", "tags": ["sfx"],
     "description": "Generate SFX from text prompt.",
     "nodes": [_n("sf", "sfx_generate", "audio_generation")]},

    # ============ ANNOTATION (8) ============
    {"id": "tpl-ann-001", "category": "annotation",
     "name": "Image Classification Annotate",
     "tags": ["classification"],
     "description": "Classify images into categories.",
     "nodes": [_n("pl", "prelabel", "prelabel"),
               _n("an", "annotate", "annotation", "pl"),
               _n("rv", "review", "review", "an")]},
    {"id": "tpl-ann-002", "category": "annotation",
     "name": "Bounding Box Detect", "tags": ["bbox", "detection"],
     "description": "Annotate object bounding boxes.",
     "nodes": [_n("pl", "prelabel_bbox", "prelabel"),
               _n("an", "bbox_annotate", "annotation", "pl"),
               _n("qa", "qa_check", "quality", "an")]},
    {"id": "tpl-ann-003", "category": "annotation",
     "name": "Polygon Segmentation",
     "tags": ["polygon", "seg"],
     "description": "Polygon-based instance segmentation.",
     "nodes": [_n("sm", "sam_prelabel", "prelabel"),
               _n("an", "polygon_annotate", "annotation", "sm"),
               _n("rv", "review", "review", "an")]},
    {"id": "tpl-ann-004", "category": "annotation",
     "name": "Dense Caption", "tags": ["caption", "dense"],
     "description": "Generate dense captions per region.",
     "nodes": [_n("cg", "caption_gen", "generation"),
               _n("an", "human_review", "annotation", "cg")]},
    {"id": "tpl-ann-005", "category": "annotation",
     "name": "OCR Annotation", "tags": ["ocr"],
     "description": "Detect and transcribe text regions.",
     "nodes": [_n("oc", "ocr_prelabel", "prelabel"),
               _n("an", "annotate_text", "annotation", "oc"),
               _n("rv", "review", "review", "an")]},
    {"id": "tpl-ann-006", "category": "annotation",
     "name": "Pose Keypoints", "tags": ["pose", "keypoints"],
     "description": "Annotate body pose keypoints.",
     "nodes": [_n("pk", "pose_prelabel", "prelabel"),
               _n("an", "keypoint_annotate", "annotation", "pk")]},
    {"id": "tpl-ann-007", "category": "annotation",
     "name": "Video Temporal Annotate",
     "tags": ["video", "temporal"],
     "description": "Time-stamped action annotations on video.",
     "nodes": [_n("sh", "shot_detect", "preprocessing"),
               _n("an", "temporal_annotate", "annotation", "sh"),
               _n("rv", "review", "review", "an", retry_max=1)]},
    {"id": "tpl-ann-008", "category": "annotation",
     "name": "Multi-Reviewer Consensus",
     "tags": ["consensus", "agreement"],
     "description": "3 reviewers + agreement engine.",
     "nodes": [_n("a1", "reviewer_a", "annotation"),
               _n("a2", "reviewer_b", "annotation"),
               _n("a3", "reviewer_c", "annotation"),
               _n("ag", "agreement", "consensus", "a1", "a2", "a3")]},

    # ============ CLEANING (6) ============
    {"id": "tpl-cln-001", "category": "cleaning",
     "name": "Image Dedup Pipeline",
     "tags": ["dedup", "phash"],
     "description": "Perceptual hash dedup.",
     "nodes": [_n("ph", "phash", "cleaning"),
               _n("dd", "dedup", "cleaning", "ph")]},
    {"id": "tpl-cln-002", "category": "cleaning",
     "name": "NSFW Filter", "tags": ["nsfw", "safety"],
     "description": "Drop NSFW samples.",
     "nodes": [_n("nf", "nsfw_classify", "cleaning")]},
    {"id": "tpl-cln-003", "category": "cleaning",
     "name": "Blur Detection + Drop",
     "tags": ["blur", "quality"],
     "description": "Laplacian-variance blur filter.",
     "nodes": [_n("bd", "blur_detect", "cleaning"),
               _n("dr", "drop_blurry", "cleaning", "bd")]},
    {"id": "tpl-cln-004", "category": "cleaning",
     "name": "OCR Cleanup (text-in-image)",
     "tags": ["ocr", "watermark"],
     "description": "Detect and remove text/watermarks.",
     "nodes": [_n("oc", "ocr", "cleaning"),
               _n("rm", "remove_text", "cleaning", "oc")]},
    {"id": "tpl-cln-005", "category": "cleaning",
     "name": "Face Quality Filter",
     "tags": ["face", "quality"],
     "description": "Drop low-quality faces.",
     "nodes": [_n("fd", "face_detect", "cleaning"),
               _n("fq", "face_quality", "cleaning", "fd")]},
    {"id": "tpl-cln-006", "category": "cleaning",
     "name": "Aspect-Ratio Normalize",
     "tags": ["aspect", "resize"],
     "description": "Center-crop or pad to target AR.",
     "nodes": [_n("ar", "ar_normalize", "cleaning")]},

    # ============ SCORING (5) ============
    {"id": "tpl-scr-001", "category": "scoring",
     "name": "Aesthetic Rank", "tags": ["aesthetic", "rank"],
     "description": "Compute aesthetic scores, keep top-K.",
     "nodes": [_n("as", "aesthetic_score", "scoring"),
               _n("rk", "rank_topk", "scoring", "as")]},
    {"id": "tpl-scr-002", "category": "scoring",
     "name": "Clip-Score Filter",
     "tags": ["clip", "alignment"],
     "description": "Text-image alignment score.",
     "nodes": [_n("cl", "clip_score", "scoring")]},
    {"id": "tpl-scr-003", "category": "scoring",
     "name": "Diversity Score", "tags": ["diversity"],
     "description": "Pairwise diversity scoring.",
     "nodes": [_n("dv", "diversity", "scoring")]},
    {"id": "tpl-scr-004", "category": "scoring",
     "name": "Composite Quality",
     "tags": ["quality", "composite"],
     "description": "Aesthetic + clip + diversity composite.",
     "nodes": [_n("as", "aesthetic", "scoring"),
               _n("cl", "clip", "scoring"),
               _n("dv", "diversity", "scoring"),
               _n("cp", "composite", "scoring", "as", "cl", "dv")]},
    {"id": "tpl-scr-005", "category": "scoring",
     "name": "Reward Model Score", "tags": ["reward", "rlhf"],
     "description": "Reward model inference.",
     "nodes": [_n("rm", "reward_score", "scoring")]},

    # ============ DATASET (5) ============
    {"id": "tpl-ds-001", "category": "dataset",
     "name": "Build Image Dataset",
     "tags": ["dataset", "build"],
     "description": "Assemble versioned dataset.",
     "nodes": [_n("co", "collect", "collection"),
               _n("cl", "clean", "cleaning", "co"),
               _n("sc", "score", "scoring", "cl"),
               _n("vr", "version", "dataset", "sc")]},
    {"id": "tpl-ds-002", "category": "dataset",
     "name": "Sample + Export", "tags": ["sample", "export"],
     "description": "Sample N items and export.",
     "nodes": [_n("sa", "sample", "dataset"),
               _n("ex", "export", "export", "sa")]},
    {"id": "tpl-ds-003", "category": "dataset",
     "name": "Train/Val/Test Split", "tags": ["split"],
     "description": "Random split with stratification.",
     "nodes": [_n("sp", "split", "dataset")]},
    {"id": "tpl-ds-004", "category": "dataset",
     "name": "Augment Dataset", "tags": ["augment"],
     "description": "Apply geometric / colour augmentation.",
     "nodes": [_n("au", "augment", "preprocessing")]},
    {"id": "tpl-ds-005", "category": "dataset",
     "name": "Dataset Card Render", "tags": ["docs", "card"],
     "description": "Generate dataset card markdown.",
     "nodes": [_n("st", "stats", "analysis"),
               _n("cd", "render_card", "docs", "st")]},

    # ============ EXPORT (3) ============
    {"id": "tpl-exp-001", "category": "export",
     "name": "OSS Bulk Export", "tags": ["oss", "bulk"],
     "description": "Stream to S3-compatible bucket.",
     "nodes": [_n("cm", "compress", "compression"),
               _n("up", "upload", "export", "cm", retry_max=2)]},
    {"id": "tpl-exp-002", "category": "export",
     "name": "Parquet Bundle", "tags": ["parquet"],
     "description": "Pack into Parquet shards.",
     "nodes": [_n("pq", "parquet_pack", "export")]},
    {"id": "tpl-exp-003", "category": "export",
     "name": "HuggingFace Hub Upload",
     "tags": ["hf", "hub"],
     "description": "Push dataset to HF Hub.",
     "nodes": [_n("hf", "hf_upload", "export", retry_max=2)]},

    # ============ OPS (3) ============
    {"id": "tpl-ops-001", "category": "ops",
     "name": "Health Self-Check", "tags": ["health"],
     "description": "Run all engine health probes.",
     "nodes": [_n("hc", "healthcheck", "ops")]},
    {"id": "tpl-ops-002", "category": "ops",
     "name": "Vector Index Refresh",
     "tags": ["vector", "index"],
     "description": "Rebuild vector index from latest.",
     "nodes": [_n("vr", "vector_refresh", "ops", retry_max=1)]},
    {"id": "tpl-ops-003", "category": "ops",
     "name": "Daily Cleanup Sweep",
     "tags": ["cleanup", "cron"],
     "description": "Tidy orphan files + dedup DB.",
     "nodes": [_n("od", "orphan_detect", "cleaning"),
               _n("dd", "dedup_db", "cleaning", "od")]},
]


__all__ = ["_BASE_TEMPLATES"]