"""P3-6-W2: 10 mixed business pipeline templates.

These combine multiple stages (collect / clean / annotate / score /
filter / export) into complete training-data pipelines that map to the
major LMM training regimes:

  * Pretrain (image)
  * SFT (image-classification / image-caption / video-caption / text-ner)
  * DPO preference
  * RLHF reward
  * Multimodal SFT (image+text)
  * Video-edit SFT
  * Short-drama SFT
"""
from __future__ import annotations

from typing import Any, Dict, List

from ._helpers import _n, _meta


_PIPELINE_TEMPLATES: List[Dict[str, Any]] = [

    # ---- 1. Image pretrain end-to-end -------------------------------
    {"id": "tpl-biz-pipe-001", "category": "pipeline",
     "name": "Image Pretrain Pipeline",
     "tags": ["pretrain", "image", "laion", "caption"],
     "description": ("Full image pretrain pipeline: collect -> dedup -> "
                     "blur/NSFW filter -> aesthetic+CLIP score -> "
                     "top-K -> Parquet export."),
     "version": "1.0.0",
     **_meta(
         inputs={
             "sources": {"type": "array<object>", "required": True,
                          "description": "[{type: 'hf'|'web'|'oss', "
                                         "...}]"},
             "target_count": {"type": "int", "default": 1000000},
             "min_aesthetic": {"type": "float", "default": 5.0},
             "min_clip": {"type": "float", "default": 0.20},
             "oss_bucket": {"type": "string", "default": "pretrain-img"},
         },
         outputs=["manifest.jsonl", "parquet/*.parquet",
                  "stats.json", "card.md"],
         steps=[
             {"id": "col", "name": "Multi-source Collect",
              "operator": "collection.multi_source",
              "config": {"sources": "$inputs.sources"}},
             {"id": "ded", "name": "pHash Dedup",
              "operator": "cleaning.phash_dedup"},
             {"id": "flt", "name": "Quality + Safety Filter",
              "operator": "cleaning.quality_filter",
              "config": {"checks": ["blur", "nsfw", "ocr_text"]}},
             {"id": "asc", "name": "Aesthetic + CLIP Score",
              "operator": "scoring.composite",
              "config": {"score_keys": ["aesthetic", "clip"]}},
             {"id": "tk", "name": "Top-K Selection",
              "operator": "dataset.topk",
              "config": {"k": "$inputs.target_count",
                         "min_aesthetic": "$inputs.min_aesthetic",
                         "min_clip": "$inputs.min_clip"}},
             {"id": "wr", "name": "Parquet Export",
              "operator": "export.to_parquet",
              "config": {"shard_size_mb": 500}},
             {"id": "up", "name": "OSS Upload",
              "operator": "oss.upload",
              "config": {"bucket": "$inputs.oss_bucket"}},
         ],
         metrics=["collected", "after_dedup", "after_filter",
                  "scored", "kept", "duration_seconds"],
     ),
     "nodes": [_n("col", "collect", "collection"),
               _n("ded", "dedup", "cleaning", "col"),
               _n("flt", "quality_filter", "cleaning", "ded"),
               _n("asc", "composite_score", "scoring", "flt"),
               _n("tk", "topk", "dataset", "asc"),
               _n("wr", "parquet_export", "export", "tk"),
               _n("up", "oss_upload", "export", "wr", retry_max=2)]},

    # ---- 2. SFT image classification ---------------------------------
    {"id": "tpl-biz-pipe-002", "category": "pipeline",
     "name": "SFT Image Classification Pipeline",
     "tags": ["sft", "image-classification", "alpaca"],
     "description": ("SFT pipeline for image classification: collect -> "
                     "clean -> classify-annotate -> review -> "
                     "score -> Alpaca export."),
     "version": "1.0.0",
     **_meta(
         inputs={
             "sources": {"type": "array<object>", "required": True},
             "labels": {"type": "array<string>", "required": True},
             "reviewers": {"type": "int", "default": 2, "min": 1, "max": 5},
             "oss_bucket": {"type": "string", "default": "sft-cls"},
         },
         outputs=["alpaca.jsonl", "stats.json"],
         steps=[
             {"id": "col", "name": "Collect", "operator": "collection.multi_source"},
             {"id": "cln", "name": "Clean (blur/NSFW)",
              "operator": "cleaning.quality_filter"},
             {"id": "pl", "name": "Pre-label (CLIP zero-shot)",
              "operator": "annotation.prelabel_classify",
              "config": {"labels": "$inputs.labels"}},
             {"id": "an", "name": "Human Annotate",
              "operator": "annotation.classify",
              "config": {"labels": "$inputs.labels",
                         "reviewers": "$inputs.reviewers"}},
             {"id": "ag", "name": "Consensus Aggregate",
              "operator": "annotation.consensus",
              "config": {"min_agreement": 0.6}},
             {"id": "sc", "name": "Score (CLIP + aesthetic)",
              "operator": "scoring.composite"},
             {"id": "alp", "name": "Alpaca Export",
              "operator": "format.alpaca_export"},
             {"id": "up", "name": "OSS Upload",
              "operator": "oss.upload",
              "config": {"bucket": "$inputs.oss_bucket"}},
         ],
         metrics=["collected", "labeled", "consensus_kept",
                  "alpaca_rows", "duration_seconds"],
     ),
     "nodes": [_n("col", "collect", "collection"),
               _n("cln", "clean", "cleaning", "col"),
               _n("pl", "prelabel", "prelabel", "cln"),
               _n("an", "annotate", "annotation", "pl"),
               _n("ag", "consensus", "consensus", "an"),
               _n("sc", "score", "scoring", "ag"),
               _n("alp", "alpaca_export", "export", "sc"),
               _n("up", "oss_upload", "export", "alp")]},

    # ---- 3. SFT image caption ----------------------------------------
    {"id": "tpl-biz-pipe-003", "category": "pipeline",
     "name": "SFT Image Caption Pipeline",
     "tags": ["sft", "image-caption", "llava", "sharegpt"],
     "description": ("SFT image-caption pipeline: collect -> clean -> "
                     "dense caption (VLM) -> human review -> "
                     "ShareGPT export."),
     "version": "1.0.0",
     **_meta(
         inputs={
             "sources": {"type": "array<object>", "required": True},
             "caption_model": {"type": "string",
                                "default": "llava-1.5-13b"},
             "review_threshold": {"type": "float", "default": 0.7,
                                   "min": 0.0, "max": 1.0},
             "oss_bucket": {"type": "string", "default": "sft-cap"},
         },
         outputs=["sharegpt.json", "stats.json"],
         steps=[
             {"id": "col", "name": "Collect",
              "operator": "collection.multi_source"},
             {"id": "cln", "name": "Clean",
              "operator": "cleaning.quality_filter"},
             {"id": "cg", "name": "VLM Caption",
              "operator": "annotation.vlm_caption",
              "config": {"model": "$inputs.caption_model"}},
             {"id": "rv", "name": "Human Review",
              "operator": "annotation.review",
              "config": {"approve_threshold": "$inputs.review_threshold"}},
             {"id": "wr", "name": "ShareGPT Export",
              "operator": "format.sharegpt_export"},
             {"id": "up", "name": "OSS Upload",
              "operator": "oss.upload",
              "config": {"bucket": "$inputs.oss_bucket"}},
         ],
         metrics=["collected", "captioned", "approved",
                  "exported", "duration_seconds"],
     ),
     "nodes": [_n("col", "collect", "collection"),
               _n("cln", "clean", "cleaning", "col"),
               _n("cg", "vlm_caption", "annotation", "cln"),
               _n("rv", "review", "review", "cg"),
               _n("wr", "sharegpt_export", "export", "rv"),
               _n("up", "oss_upload", "export", "wr")]},

    # ---- 4. SFT video caption ----------------------------------------
    {"id": "tpl-biz-pipe-004", "category": "pipeline",
     "name": "SFT Video Caption Pipeline",
     "tags": ["sft", "video-caption", "sharegpt"],
     "description": ("Video caption SFT: collect clips -> key-frame "
                     "extract -> caption per shot -> review -> "
                     "ShareGPT export."),
     "version": "1.0.0",
     **_meta(
         inputs={
             "sources": {"type": "array<object>", "required": True},
             "shot_method": {"type": "string", "default": "transnetv2"},
             "fps_sample": {"type": "int", "default": 1, "min": 1, "max": 10},
             "oss_bucket": {"type": "string", "default": "sft-vcap"},
         },
         outputs=["sharegpt.json", "shot_meta.json", "stats.json"],
         steps=[
             {"id": "col", "name": "Video Collect",
              "operator": "collection.video_source"},
             {"id": "sh", "name": "Shot Detection",
              "operator": "preprocessing.shot_detect",
              "config": {"method": "$inputs.shot_method"}},
             {"id": "kf", "name": "Key-Frame Sample",
              "operator": "preprocessing.keyframe_sample",
              "config": {"fps": "$inputs.fps_sample"}},
             {"id": "cg", "name": "Shot Caption (VLM)",
              "operator": "annotation.vlm_shot_caption"},
             {"id": "rv", "name": "Human Review",
              "operator": "annotation.review"},
             {"id": "wr", "name": "ShareGPT Export",
              "operator": "format.sharegpt_export"},
             {"id": "up", "name": "OSS Upload",
              "operator": "oss.upload",
              "config": {"bucket": "$inputs.oss_bucket"}},
         ],
         metrics=["videos", "shots", "keyframes", "captions",
                  "approved", "duration_seconds"],
     ),
     "nodes": [_n("col", "collect_video", "collection"),
               _n("sh", "shot_detect", "preprocessing", "col"),
               _n("kf", "keyframe_sample", "preprocessing", "sh"),
               _n("cg", "vlm_caption", "annotation", "kf"),
               _n("rv", "review", "review", "cg"),
               _n("wr", "sharegpt_export", "export", "rv"),
               _n("up", "oss_upload", "export", "wr")]},

    # ---- 5. SFT text NER --------------------------------------------
    {"id": "tpl-biz-pipe-005", "category": "pipeline",
     "name": "SFT Text NER Pipeline",
     "tags": ["sft", "text-ner", "token-classification"],
     "description": ("Text NER SFT: crawl text -> sentence split -> "
                     "BIO prelabel -> human annotate -> BIO validate "
                     "-> Alpaca export."),
     "version": "1.0.0",
     **_meta(
         inputs={
             "sources": {"type": "array<object>", "required": True},
             "entity_types": {"type": "array<string>", "required": True},
             "model": {"type": "string", "default": "bert-base-ner"},
             "oss_bucket": {"type": "string", "default": "sft-ner"},
         },
         outputs=["alpaca.jsonl", "bio.jsonl", "stats.json"],
         steps=[
             {"id": "col", "name": "Text Collect",
              "operator": "collection.text_source"},
             {"id": "sp", "name": "Sentence Split",
              "operator": "preprocessing.sentence_split"},
             {"id": "pl", "name": "BIO Prelabel",
              "operator": "annotation.bio_prelabel",
              "config": {"entity_types": "$inputs.entity_types",
                         "model": "$inputs.model"}},
             {"id": "an", "name": "Human BIO Annotate",
              "operator": "annotation.bio_annotate",
              "config": {"entity_types": "$inputs.entity_types"}},
             {"id": "vl", "name": "BIO Schema Validate",
              "operator": "annotation.bio_validate"},
             {"id": "wr", "name": "Alpaca Export",
              "operator": "format.alpaca_ner_export"},
             {"id": "up", "name": "OSS Upload",
              "operator": "oss.upload",
              "config": {"bucket": "$inputs.oss_bucket"}},
         ],
         metrics=["sentences", "tokens", "entities",
                  "alpaca_rows", "duration_seconds"],
     ),
     "nodes": [_n("col", "collect_text", "collection"),
               _n("sp", "sentence_split", "preprocessing", "col"),
               _n("pl", "bio_prelabel", "prelabel", "sp"),
               _n("an", "bio_annotate", "annotation", "pl"),
               _n("vl", "bio_validate", "export", "an"),
               _n("wr", "alpaca_export", "export", "vl"),
               _n("up", "oss_upload", "export", "wr")]},

    # ---- 6. DPO preference ------------------------------------------
    {"id": "tpl-biz-pipe-006", "category": "pipeline",
     "name": "DPO Preference Pipeline",
     "tags": ["dpo", "preference", "rlhf", "pair"],
     "description": ("DPO data pipeline: collect prompts -> generate K "
                     "responses -> reward score -> pair chosen/rejected "
                     "-> DPO JSONL export."),
     "version": "1.0.0",
     **_meta(
         inputs={
             "prompt_source": {"type": "object", "required": True},
             "k_responses": {"type": "int", "default": 4, "min": 2, "max": 16},
             "reward_model": {"type": "string", "default": "skywork-rm"},
             "margin": {"type": "float", "default": 0.5,
                        "description": "min chosen-rejected reward gap"},
             "oss_bucket": {"type": "string", "default": "dpo"},
         },
         outputs=["dpo.jsonl", "stats.json"],
         steps=[
             {"id": "ld", "name": "Load Prompts",
              "operator": "dataset.load_prompts",
              "config": {"source": "$inputs.prompt_source"}},
             {"id": "gen", "name": "Generate K Responses",
              "operator": "generation.sample",
              "config": {"k": "$inputs.k_responses",
                         "temperature": [0.7, 0.9, 1.1, 1.3]}},
             {"id": "rm", "name": "Reward Score",
              "operator": "scoring.reward",
              "config": {"model": "$inputs.reward_model"}},
             {"id": "pair", "name": "Pair Chosen/Rejected",
              "operator": "dataset.pair_preference",
              "config": {"margin": "$inputs.margin"}},
             {"id": "wr", "name": "DPO JSONL Export",
              "operator": "export.write_dpo"},
             {"id": "up", "name": "OSS Upload",
              "operator": "oss.upload",
              "config": {"bucket": "$inputs.oss_bucket"}},
         ],
         metrics=["prompts", "responses", "pairs_kept",
                  "avg_margin", "duration_seconds"],
     ),
     "nodes": [_n("ld", "load_prompts", "collection"),
               _n("gn", "sample_responses", "generation", "ld"),
               _n("rm", "reward_score", "scoring", "gn"),
               _n("pr", "pair_preference", "dataset", "rm"),
               _n("wr", "write_dpo", "export", "pr"),
               _n("up", "oss_upload", "export", "wr")]},

    # ---- 7. RLHF reward model ---------------------------------------
    {"id": "tpl-biz-pipe-007", "category": "pipeline",
     "name": "RLHF Reward Model Pipeline",
     "tags": ["rlhf", "reward-model", "ranking"],
     "description": ("Reward-model training data: collect prompts -> "
                     "sample K -> human rank -> Bradley-Terry convert "
                     "-> parquet export."),
     "version": "1.0.0",
     **_meta(
         inputs={
             "prompt_source": {"type": "object", "required": True},
             "k": {"type": "int", "default": 4, "min": 2, "max": 8},
             "rankers_per_group": {"type": "int", "default": 3},
             "oss_bucket": {"type": "string", "default": "rm-data"},
         },
         outputs=["rm_ranking.jsonl", "rm_pairwise.jsonl", "stats.json"],
         steps=[
             {"id": "ld", "name": "Load Prompts",
              "operator": "dataset.load_prompts"},
             {"id": "gen", "name": "Sample K Responses",
              "operator": "generation.sample",
              "config": {"k": "$inputs.k"}},
             {"id": "rk", "name": "Human Ranking",
              "operator": "annotation.ranking",
              "config": {"rankers": "$inputs.rankers_per_group"}},
             {"id": "bt", "name": "Bradley-Terry Pairs",
              "operator": "dataset.bradley_terry"},
             {"id": "wr", "name": "Parquet Export",
              "operator": "export.to_parquet"},
             {"id": "up", "name": "OSS Upload",
              "operator": "oss.upload",
              "config": {"bucket": "$inputs.oss_bucket"}},
         ],
         metrics=["prompts", "rankings", "pairwise_rows",
                  "duration_seconds"],
     ),
     "nodes": [_n("ld", "load_prompts", "collection"),
               _n("gn", "sample_responses", "generation", "ld"),
               _n("rk", "human_ranking", "annotation", "gn"),
               _n("bt", "bradley_terry", "dataset", "rk"),
               _n("wr", "parquet_export", "export", "bt"),
               _n("up", "oss_upload", "export", "wr")]},

    # ---- 8. Multimodal SFT -----------------------------------------
    {"id": "tpl-biz-pipe-008", "category": "pipeline",
     "name": "Multimodal SFT Pipeline",
     "tags": ["multimodal", "sft", "vision-language"],
     "description": ("Image+text SFT: collect paired data -> image+text "
                     "align -> quality filter -> conversation format "
                     "-> ShareGPT export."),
     "version": "1.0.0",
     **_meta(
         inputs={
             "image_sources": {"type": "array<object>", "required": True},
             "text_sources": {"type": "array<object>", "required": True},
             "min_clip": {"type": "float", "default": 0.25},
             "oss_bucket": {"type": "string", "default": "mm-sft"},
         },
         outputs=["sharegpt.json", "parquet/*.parquet", "stats.json"],
         steps=[
             {"id": "ic", "name": "Image Collect",
              "operator": "collection.image_source",
              "config": {"sources": "$inputs.image_sources"}},
             {"id": "tc", "name": "Text Collect",
              "operator": "collection.text_source",
              "config": {"sources": "$inputs.text_sources"}},
             {"id": "al", "name": "Image-Text Align",
              "operator": "dataset.align_mm",
              "config": {"key": "image_id"}},
             {"id": "cln", "name": "Quality Filter",
              "operator": "cleaning.quality_filter"},
             {"id": "al2", "name": "CLIP Filter",
              "operator": "scoring.clip_filter",
              "config": {"min": "$inputs.min_clip"}},
             {"id": "fmt", "name": "Conversation Format",
              "operator": "format.sharegpt_export"},
             {"id": "up", "name": "OSS Upload",
              "operator": "oss.upload",
              "config": {"bucket": "$inputs.oss_bucket"}},
         ],
         metrics=["images", "texts", "aligned_pairs",
                  "after_clip", "sharegpt_rows"],
     ),
     "nodes": [_n("ic", "image_collect", "collection"),
               _n("tc", "text_collect", "collection"),
               _n("al", "align_mm", "dataset", "ic", "tc"),
               _n("cln", "quality_filter", "cleaning", "al"),
               _n("sc", "clip_filter", "scoring", "cln"),
               _n("fm", "sharegpt_format", "export", "sc"),
               _n("up", "oss_upload", "export", "fm")]},

    # ---- 9. Video-edit SFT ------------------------------------------
    {"id": "tpl-biz-pipe-009", "category": "pipeline",
     "name": "Video Edit SFT Pipeline",
     "tags": ["video-edit", "sft", "instruction"],
     "description": ("Video-edit instruction SFT: collect source/target "
                     "pairs -> describe edit -> human review -> "
                     "Alpaca export."),
     "version": "1.0.0",
     **_meta(
         inputs={
             "source_clips": {"type": "array<object>", "required": True},
             "target_clips": {"type": "array<object>", "required": True},
             "edit_model": {"type": "string", "default": "videocap-7b"},
             "oss_bucket": {"type": "string", "default": "videoedit-sft"},
         },
         outputs=["alpaca.jsonl", "stats.json"],
         steps=[
             {"id": "ld", "name": "Load Source/Target Pairs",
              "operator": "dataset.load_pairs",
              "config": {"source": "$inputs.source_clips",
                         "target": "$inputs.target_clips"}},
             {"id": "kf", "name": "Key-Frame Extract",
              "operator": "preprocessing.keyframe_sample"},
             {"id": "cap", "name": "Edit Description (VLM)",
              "operator": "annotation.vlm_diff_caption",
              "config": {"model": "$inputs.edit_model"}},
             {"id": "rv", "name": "Human Review",
              "operator": "annotation.review"},
             {"id": "wr", "name": "Alpaca Export",
              "operator": "format.alpaca_export"},
             {"id": "up", "name": "OSS Upload",
              "operator": "oss.upload",
              "config": {"bucket": "$inputs.oss_bucket"}},
         ],
         metrics=["pairs", "captions", "approved",
                  "alpaca_rows", "duration_seconds"],
     ),
     "nodes": [_n("ld", "load_pairs", "collection"),
               _n("kf", "keyframe_sample", "preprocessing", "ld"),
               _n("cp", "vlm_diff_caption", "annotation", "kf"),
               _n("rv", "review", "review", "cp"),
               _n("wr", "alpaca_export", "export", "rv"),
               _n("up", "oss_upload", "export", "wr")]},

    # ---- 10. Short-drama SFT ----------------------------------------
    {"id": "tpl-biz-pipe-010", "category": "pipeline",
     "name": "Short Drama SFT Pipeline",
     "tags": ["short-drama", "sft", "narrative"],
     "description": ("Short-drama SFT: script -> storyboard -> shot "
                     "video -> caption -> dialogue -> ShareGPT export."),
     "version": "1.0.0",
     **_meta(
         inputs={
             "script_source": {"type": "object", "required": True},
             "tts_model": {"type": "string", "default": "cosyvoice"},
             "video_model": {"type": "string", "default": "cogvideox"},
             "oss_bucket": {"type": "string", "default": "drama-sft"},
         },
         outputs=["sharegpt.json", "episodes/*.mp4",
                  "audio/*.wav", "stats.json"],
         steps=[
             {"id": "sc", "name": "Script Parse",
              "operator": "scripting.parse",
              "config": {"source": "$inputs.script_source"}},
             {"id": "sb", "name": "Storyboard",
              "operator": "preprocessing.storyboard"},
             {"id": "vs", "name": "Shot Video Generation",
              "operator": "video_generation.shot",
              "config": {"model": "$inputs.video_model"}},
             {"id": "au", "name": "Dialogue TTS",
              "operator": "audio.tts",
              "config": {"model": "$inputs.tts_model"}},
             {"id": "ed", "name": "Compose Episode",
              "operator": "video_compose.episode"},
             {"id": "cp", "name": "Episode Caption",
              "operator": "annotation.vlm_episode_caption"},
             {"id": "wr", "name": "ShareGPT Export",
              "operator": "format.sharegpt_export"},
             {"id": "up", "name": "OSS Upload",
              "operator": "oss.upload",
              "config": {"bucket": "$inputs.oss_bucket"}},
         ],
         metrics=["scripts", "shots", "episodes",
                  "captions", "duration_seconds"],
     ),
     "nodes": [_n("sc", "script_parse", "scripting"),
               _n("sb", "storyboard", "preprocessing", "sc"),
               _n("vs", "shot_video", "video_generation", "sb"),
               _n("au", "tts", "audio", "sc"),
               _n("ed", "compose_episode", "video_compose", "vs", "au"),
               _n("cp", "episode_caption", "annotation", "ed"),
               _n("wr", "sharegpt_export", "export", "cp"),
               _n("up", "oss_upload", "export", "wr")]},
]


__all__ = ["_PIPELINE_TEMPLATES"]