CREATE TABLE generation_tasks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    project_id UUID REFERENCES projects(id) ON DELETE SET NULL,
    module_type TEXT NOT NULL CHECK (module_type IN ('image-gen',
    'image-edit',
    'video-gen',
    '3d-gen')),
    prompt TEXT NOT NULL,
    negative_prompt TEXT,
    model_config JSONB DEFAULT '{}',
    parameters JSONB DEFAULT '{}',
    input_files TEXT[] DEFAULT '{}',
    output_files TEXT[] DEFAULT '{}',
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending',
    'processing',
    'completed',
    'failed',
    'cancelled')),
    progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
    error_message TEXT,
    execution_time INTEGER,
    memory_usage INTEGER,
    gpu_usage INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);