"""P15-A1: SQLAlchemy ORM models for quota persistence.

Replaces :class:`billing.quotas.InMemoryQuotaTracker` with a SQL-backed layer
that survives process restart, supports multi-process access, and is auditable.

4 tables (single source of truth for quota state):

1. ``quota_usage``     — current qty per (user_id, dimension). PK = composite.
                         1 row per active (user, dimension). Updated on every
                         :meth:`DBQuotaTracker.record` / :meth:`reset`.
2. ``quota_event``     — append-only event log. Every record() writes 1 row.
                         PK = autoincrement id. Used for audit + replay.
3. ``quota_reset_log`` — explicit reset audit trail. 1 row per admin/user reset
                         (actor + prev_qty + new_qty). PK = autoincrement id.
4. ``quota_decision_log`` — every :meth:`QuotaService.check` writes 1 row.
                            PK = autoincrement id. Used for forensic "why was
                            this user blocked at 14:32?" lookups.

Schema compatibility:
- All tables share the same ``Base`` from :mod:`billing.db` (declarative_base),
  so they coexist with ``Wallet`` / ``BillingOrder`` / ``BillingSubscription``
  in one database (``backend/data/billing.db`` by default).
- SQLite (dev) ↔ PostgreSQL (prod) — column types are dialect-portable:
  ``String`` / ``Integer`` / ``BigInteger`` / ``DateTime``.
- Idempotent ``init_quota_db()`` — safe to call at every startup.

Naming note:
- Table names use the ``quota_`` prefix (not ``billing_quota_``) to keep the
  namespace clean and to differentiate from the older ``billing_usage_log``
  DDL strings (which are still exported from :mod:`billing.quotas` for
  backward-compat).
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import (
    BigInteger, Column, DateTime, Index, Integer, String,
)
from sqlalchemy.orm import Session

# Reuse the project-wide Declarative Base (so all billing tables share one
# metadata + one ``init_db()`` call).
from .db import Base, get_engine, get_session_factory


# ─── helpers ─────────────────────────────────────────────────────────────────

def _utcnow_naive() -> datetime:
    """Return ``datetime.now(timezone.utc)`` as a naive UTC ``datetime``.

    Matches the convention used by :mod:`billing.db` (so the column values
    compare correctly across tables without tz-aware vs tz-naive surprises).
    """
    return datetime.now(timezone.utc).replace(tzinfo=None)


# ─── 1. quota_usage ──────────────────────────────────────────────────────────

class QuotaUsage(Base):
    """Current accumulated usage per (user_id, dimension).

    Primary key is the composite (user_id, dimension) — at most one row per
    pair. No surrogate ``id`` column: SQLite forbids autoincrement on a
    composite PK, and the composite itself is already a unique identity
    (we always query / upsert by (user_id, dimension)).

    Index:
        ``ix_quota_usage_user_updated (user_id, last_updated)`` — supports
        "show me this user's recent activity" queries without scanning
        the full table.
    """
    __tablename__ = "quota_usage"

    user_id = Column(String(64), nullable=False, primary_key=True)
    dimension = Column(String(40), nullable=False, primary_key=True)
    qty = Column(BigInteger, nullable=False, default=0)
    last_updated = Column(DateTime, nullable=False, default=_utcnow_naive,
                          onupdate=_utcnow_naive)

    __table_args__ = (
        Index("ix_quota_usage_user_updated", "user_id", "last_updated"),
        Index("ix_quota_usage_dimension", "dimension"),
    )

    def to_dict(self) -> dict:
        return {
            "user_id": self.user_id,
            "dimension": self.dimension,
            "qty": int(self.qty),
            "last_updated": (self.last_updated.isoformat()
                             if self.last_updated else None),
        }


# ─── 2. quota_event ──────────────────────────────────────────────────────────

class QuotaEvent(Base):
    """Append-only event log of every ``record()`` call.

    Each insert is one ``record(user, dim, qty)`` invocation. Used for:
    - Audit: who consumed how much, when, and why (ref_id = order_id, job_id, etc.).
    - Replay: rebuild ``quota_usage`` from this log if it ever drifts.

    Note on ``id`` type: ``Integer`` (not ``BigInteger``) is used here so
    SQLite picks up the implicit ROWID autoincrement (``INTEGER PRIMARY KEY``
    is the magic SQLite idiom). On PostgreSQL, ``Integer`` becomes SERIAL /
    ``INT GENERATED BY DEFAULT AS IDENTITY`` — both autoincrement. ``Integer``
    supports up to 2.1B rows, which is plenty for an event log.

    Index:
        ``ix_quota_event_user_dim_ts (user_id, dimension, ts)`` — covers the
        most common query: "show me user X's events on dimension Y in the last
        N hours" without a full scan.
    """
    __tablename__ = "quota_event"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String(64), nullable=False)
    dimension = Column(String(40), nullable=False)
    delta = Column(Integer, nullable=False, default=0)
    event_type = Column(String(20), nullable=False, default="consume")
    ref_id = Column(String(120), nullable=True, default="")
    ts = Column(DateTime, nullable=False, default=_utcnow_naive, index=True)

    __table_args__ = (
        Index("ix_quota_event_user_dim_ts", "user_id", "dimension", "ts"),
    )

    def to_dict(self) -> dict:
        return {
            "id": int(self.id) if self.id else None,
            "user_id": self.user_id,
            "dimension": self.dimension,
            "delta": int(self.delta),
            "event_type": self.event_type,
            "ref_id": self.ref_id or "",
            "ts": self.ts.isoformat() if self.ts else None,
        }


# ─── 3. quota_reset_log ──────────────────────────────────────────────────────

class QuotaResetLog(Base):
    """Audit trail of explicit resets.

    Inserted by :meth:`DBQuotaTracker.reset` when the actor is known (e.g.
    admin panel "reset user quota" button — ``actor`` field carries the
    admin user_id; for system-initiated resets, ``actor='system'``).

    Index:
        ``ix_quota_reset_user_ts (user_id, ts)`` — covers the "what changed
        for this user recently?" query used by support tools.
    """
    __tablename__ = "quota_reset_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String(64), nullable=False)
    dimension = Column(String(40), nullable=True)  # NULL = reset all dims
    prev_qty = Column(BigInteger, nullable=False, default=0)
    new_qty = Column(BigInteger, nullable=False, default=0)
    actor = Column(String(64), nullable=False, default="system")
    reason = Column(String(255), nullable=True, default="")
    ts = Column(DateTime, nullable=False, default=_utcnow_naive, index=True)

    __table_args__ = (
        Index("ix_quota_reset_user_ts", "user_id", "ts"),
    )

    def to_dict(self) -> dict:
        return {
            "id": int(self.id) if self.id else None,
            "user_id": self.user_id,
            "dimension": self.dimension,
            "prev_qty": int(self.prev_qty),
            "new_qty": int(self.new_qty),
            "actor": self.actor,
            "reason": self.reason or "",
            "ts": self.ts.isoformat() if self.ts else None,
        }


# ─── 4. quota_decision_log ───────────────────────────────────────────────────

class QuotaDecisionLog(Base):
    """Audit trail of every ``QuotaService.check`` / ``consume`` call.

    Inserted by the optional decision-logging shim in :mod:`billing.quotas`
    (only when ``QUOTA_LOG_DECISIONS=1`` is set, to avoid hot-path overhead
    in default config).

    Index:
        ``ix_quota_decision_user_dim_ts (user_id, dimension, ts)`` — covers
        "why was this user blocked?" forensics.
    """
    __tablename__ = "quota_decision_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String(64), nullable=False)
    dimension = Column(String(40), nullable=False)
    level = Column(String(20), nullable=False)  # ok / soft_warning / hard_block / unknown / infinity
    allowed = Column(Integer, nullable=False, default=1)  # 0/1 for SQL-portable bool
    plan_id = Column(String(40), nullable=False, default="")
    qty_requested = Column(Integer, nullable=False, default=1)
    current_qty = Column(BigInteger, nullable=False, default=0)
    limit_qty = Column(BigInteger, nullable=False, default=0)
    ts = Column(DateTime, nullable=False, default=_utcnow_naive, index=True)

    __table_args__ = (
        Index("ix_quota_decision_user_dim_ts", "user_id", "dimension", "ts"),
    )

    def to_dict(self) -> dict:
        return {
            "id": int(self.id) if self.id else None,
            "user_id": self.user_id,
            "dimension": self.dimension,
            "level": self.level,
            "allowed": bool(self.allowed),
            "plan_id": self.plan_id or "",
            "qty_requested": int(self.qty_requested),
            "current_qty": int(self.current_qty),
            "limit_qty": int(self.limit_qty),
            "ts": self.ts.isoformat() if self.ts else None,
        }


# ─── DDL helpers ─────────────────────────────────────────────────────────────

def init_quota_db(url: Optional[str] = None) -> None:
    """Create the 4 quota tables. Idempotent — safe at every startup.

    Calls ``Base.metadata.create_all(engine)``, which is a no-op when the
    tables already exist. Matches the ``init_db()`` pattern in
    :mod:`billing.db`.
    """
    eng = get_engine(url) if url else get_engine()
    Base.metadata.create_all(eng)


def drop_quota_db(url: Optional[str] = None) -> None:
    """Drop only the 4 quota tables (NOT the billing_wallets / orders / subs).

    Test helper — keeps Wallet / Order / Subscription data intact.
    """
    eng = get_engine(url) if url else get_engine()
    Base.metadata.drop_all(
        eng,
        tables=[QuotaUsage.__table__, QuotaEvent.__table__,
                QuotaResetLog.__table__, QuotaDecisionLog.__table__],
    )


def get_session(url: Optional[str] = None) -> Session:
    """Convenience: open a new Session against the quota tables.

    Callers are responsible for ``session.close()`` (or use as a context
    manager via ``with SessionFactory() as s:``).
    """
    factory = get_session_factory(url) if url else get_session_factory()
    return factory()


__all__ = [
    "QuotaUsage", "QuotaEvent", "QuotaResetLog", "QuotaDecisionLog",
    "init_quota_db", "drop_quota_db", "get_session",
]