#!/usr/bin/env bash
# ============================================================================
# IMDF Deployment Installer
# ============================================================================
# Usage:
#   sudo bash deploy/install.sh
#
# What it does:
#   1. Detect Python3 path
#   2. Create necessary directories (data, logs)
#   3. Install pip dependencies
#   4. Copy systemd service + enable
#   5. Create .env from template if missing
#   6. Initialize database (create_admin.py)
#   7. Start service + verify health
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SERVICE_NAME="imdf"
SERVICE_FILE="$SCRIPT_DIR/imdf.service"
SYSTEMD_DIR="/etc/systemd/system"
HEALTH_URL="http://localhost:8765/api/health"

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; }

# ── Must be root ────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root. Use: sudo bash deploy/install.sh"
    exit 1
fi

echo ""
echo "========================================="
echo "  IMDF Deployment Installer"
echo "  Project: $PROJECT_ROOT"
echo "========================================="
echo ""

# ── 1. Detect Python3 ───────────────────────────────────────────────────────
info "Step 1/7: Detecting Python3..."
PYTHON3=""
for candidate in /usr/bin/python3 /usr/local/bin/python3 /usr/bin/python3.12 /usr/bin/python3.11 /usr/bin/python3.10; do
    if [[ -x "$candidate" ]]; then
        PYTHON3="$candidate"
        break
    fi
done

if [[ -z "$PYTHON3" ]]; then
    # Fallback to `which`
    PYTHON3="$(which python3 2>/dev/null || true)"
fi

if [[ -z "$PYTHON3" ]]; then
    error "Python3 not found. Install it via: apt install python3"
    exit 1
fi

PYTHON_VERSION="$($PYTHON3 --version 2>&1)"
success "Found: $PYTHON_VERSION at $PYTHON3"

# ── 2. Create directories ───────────────────────────────────────────────────
info "Step 2/7: Creating necessary directories..."
mkdir -p "$PROJECT_ROOT/data"
mkdir -p "$PROJECT_ROOT/logs"
chown -R administrator: "$PROJECT_ROOT/data" "$PROJECT_ROOT/logs" 2>/dev/null || true
chmod 755 "$PROJECT_ROOT/data" "$PROJECT_ROOT/logs"
success "Created: data/  logs/"

# ── 3. Install pip dependencies ────────────────────────────────────────────
info "Step 3/7: Installing pip dependencies..."
REQ_FILE="$PROJECT_ROOT/requirements.txt"
if [[ ! -f "$REQ_FILE" ]]; then
    error "requirements.txt not found at $REQ_FILE"
    exit 1
fi

# Ensure pip is available
if ! $PYTHON3 -m pip --version &>/dev/null; then
    warn "pip not found, installing python3-pip..."
    apt-get update -qq && apt-get install -y -qq python3-pip
fi

info "Installing from $REQ_FILE (this may take a while)..."
$PYTHON3 -m pip install --quiet --upgrade pip
$PYTHON3 -m pip install --quiet -r "$REQ_FILE"

success "Dependencies installed"

# ── 4. Create .env from template if missing ─────────────────────────────────
info "Step 4/7: Setting up environment file..."
ENV_FILE="$PROJECT_ROOT/.env"
if [[ ! -f "$ENV_FILE" ]]; then
    cat > "$ENV_FILE" <<'ENVEOF'
# IMDF Environment Configuration
# Generated by deploy/install.sh

# Service
IMDF_PORT=8765
IMDF_HOST=0.0.0.0

# Database (SQLite by default)
DATABASE_URL=sqlite:///data/imdf.db

# Authentication (change these!)
SECRET_KEY=change-me-to-a-random-secret-key
IMDF_ADMIN_USERNAME=admin
IMDF_ADMIN_PASSWORD=admin123

# Log level
LOG_LEVEL=info

# CORS (comma-separated origins)
CORS_ORIGINS=*

# Upload limits (MB)
MAX_UPLOAD_SIZE=500
ENVEOF
    chmod 600 "$ENV_FILE"
    chown administrator: "$ENV_FILE" 2>/dev/null || true
    success "Created .env (with defaults — PLEASE EDIT SECRET_KEY and passwords!)"
else
    success ".env already exists (skipped)"
fi

# ── 5. Copy systemd service & enable ────────────────────────────────────────
info "Step 5/7: Installing systemd service..."

# Update the ExecStart line in the service file with the detected Python path
TMP_SERVICE="/tmp/imdf.service.$$"
sed "s|ExecStart=.*|ExecStart=$PYTHON3 api/canvas_web.py --port 8765|" "$SERVICE_FILE" > "$TMP_SERVICE"

cp "$TMP_SERVICE" "$SYSTEMD_DIR/${SERVICE_NAME}.service"
rm -f "$TMP_SERVICE"

chmod 644 "$SYSTEMD_DIR/${SERVICE_NAME}.service"

systemctl daemon-reload
systemctl enable "$SERVICE_NAME" 2>&1 | sed 's/^/  /'

success "Service installed and enabled: $SERVICE_NAME"

# ── 6. Initialize database ──────────────────────────────────────────────────
info "Step 6/7: Initializing database..."

# Source the .env for the create_admin script
set +u
source "$ENV_FILE" 2>/dev/null || true
set -u

cd "$PROJECT_ROOT"

# Run create_admin.py to set up the database tables + admin user
ADMIN_USER="${IMDF_ADMIN_USERNAME:-admin}"
ADMIN_PASS="${IMDF_ADMIN_PASSWORD:-admin123}"

if $PYTHON3 scripts/create_admin.py --username "$ADMIN_USER" --password "$ADMIN_PASS" --force 2>&1 | sed 's/^/  /'; then
    success "Database initialized — admin user '$ADMIN_USER' ready"
else
    warn "Database initialization returned non-zero — check output above"
fi

# ── 7. Start service ────────────────────────────────────────────────────────
info "Step 7/7: Starting IMDF service..."
systemctl restart "$SERVICE_NAME" 2>&1 | sed 's/^/  /'

# Wait for health check
info "Waiting for service to become healthy (max 30s)..."
for i in $(seq 1 15); do
    if curl -sf "$HEALTH_URL" &>/dev/null; then
        HEALTH_RESP="$(curl -sf "$HEALTH_URL" 2>/dev/null || echo '{}')"
        success "IMDF is healthy! Response: $HEALTH_RESP"
        break
    fi
    sleep 2
done

if ! curl -sf "$HEALTH_URL" &>/dev/null; then
    warn "Health check failed. Check logs: journalctl -u $SERVICE_NAME -n 50"
    echo ""
    echo "Recent logs:"
    journalctl -u "$SERVICE_NAME" --no-pager -n 20 2>&1 | sed 's/^/  /' || true
    exit 1
fi

echo ""
echo "========================================="
echo "  IMDF Deployment Complete!"
echo "========================================="
echo ""
echo "  Service:    systemctl status $SERVICE_NAME"
echo "  Logs:       journalctl -u $SERVICE_NAME -f"
echo "  Health:     curl $HEALTH_URL"
echo "  Web UI:     http://localhost:8765"
echo ""
echo "  To set up nginx reverse proxy:"
echo "    1. Edit deploy/nginx-imdf.conf (set your domain)"
echo "    2. Copy to /etc/nginx/sites-available/imdf"
echo "    3. ln -s /etc/nginx/sites-available/imdf /etc/nginx/sites-enabled/"
echo "    4. nginx -t && systemctl reload nginx"
echo ""
