"""P19 v5.3 — Meta_Kim Persistence: FailureKnowledgeBase + RunHistoryStore.

Lightweight in-memory stores backing the 7-step governance loop:

* :class:`FailureKnowledgeBase` — append-only failure records with timestamp +
  suggestion.  Backed by a JSON file so failures survive process restarts.
* :class:`RunHistoryStore` — bounded ring buffer of all :class:`GovernedRun`
  for audit + replay.  Optional JSON persistence.

Both stores are thread-safe (single ``RLock``) and serialisable to a dict
so the engine can flush them to the audit chain when governance loops finish.
"""
from __future__ import annotations

import json
import os
import threading
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _new_id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex[:12]}"


# --------------------------------------------------------------------------- #
# FailureKnowledgeBase
# --------------------------------------------------------------------------- #
class FailureKnowledgeBase:
    """Append-only failure knowledge base.

    Each record is ``{record_id, run_id, failure, context, suggestion,
    timestamp}``.  ``suggestion`` is generated by the engine when the failure
    pattern matches a known one — empty string means no suggestion yet.
    """

    def __init__(
        self,
        *,
        persist_path: Optional[str] = None,
        max_records: int = 5000,
    ) -> None:
        self._lock = threading.RLock()
        self._records: List[Dict[str, Any]] = []
        self._persist_path = persist_path
        self._max_records = max(0, int(max_records))

        if persist_path and os.path.exists(persist_path):
            try:
                with open(persist_path, "r", encoding="utf-8") as f:
                    rows = json.load(f)
                if isinstance(rows, list):
                    self._records = [r for r in rows if isinstance(r, dict)]
            except Exception:
                # best-effort; an empty KB is fine
                self._records = []

    # ----- write ----------------------------------------------------------
    def append(
        self,
        *,
        run_id: str,
        failure: str,
        context: Optional[Dict[str, Any]] = None,
        suggestion: str = "",
        tags: Optional[List[str]] = None,
    ) -> str:
        if not failure:
            raise ValueError("failure description must be non-empty")
        record_id = _new_id("fail")
        record = {
            "record_id": record_id,
            "run_id": run_id or "",
            "failure": str(failure),
            "context": dict(context or {}),
            "suggestion": str(suggestion or ""),
            "tags": list(tags or []),
            "timestamp": _now_iso(),
        }
        with self._lock:
            self._records.append(record)
            if self._max_records and len(self._records) > self._max_records:
                # FIFO trim so memory stays bounded
                self._records = self._records[-self._max_records :]
            self._persist_locked()
        return record_id

    # ----- read -----------------------------------------------------------
    def list(self, limit: int = 100) -> List[Dict[str, Any]]:
        with self._lock:
            return list(self._records[-limit:])

    def search(
        self,
        *,
        query: str = "",
        tag: Optional[str] = None,
        limit: int = 20,
    ) -> List[Dict[str, Any]]:
        q = (query or "").lower().strip()
        with self._lock:
            out: List[Dict[str, Any]] = []
            for r in self._records:
                if tag and tag not in r.get("tags", []):
                    continue
                if q and q not in r.get("failure", "").lower():
                    continue
                out.append(r)
        return out[-limit:]

    def count(self) -> int:
        with self._lock:
            return len(self._records)

    # ----- persistence ----------------------------------------------------
    def _persist_locked(self) -> None:
        if not self._persist_path:
            return
        try:
            os.makedirs(os.path.dirname(self._persist_path), exist_ok=True)
            with open(self._persist_path, "w", encoding="utf-8") as f:
                json.dump(self._records[-500:], f, ensure_ascii=False, default=str)
        except Exception:
            # best-effort persistence
            pass

    def flush(self) -> None:
        with self._lock:
            self._persist_locked()


# --------------------------------------------------------------------------- #
# RunHistoryStore
# --------------------------------------------------------------------------- #
class RunHistoryStore:
    """In-memory + JSON-persisted ring buffer of :class:`GovernedRun` records."""

    def __init__(
        self,
        *,
        persist_path: Optional[str] = None,
        max_records: int = 1000,
    ) -> None:
        self._lock = threading.RLock()
        self._records: List[Dict[str, Any]] = []
        self._persist_path = persist_path
        self._max_records = max(0, int(max_records))

        if persist_path and os.path.exists(persist_path):
            try:
                with open(persist_path, "r", encoding="utf-8") as f:
                    rows = json.load(f)
                if isinstance(rows, list):
                    self._records = [r for r in rows if isinstance(r, dict)]
            except Exception:
                self._records = []

    # ----- write ----------------------------------------------------------
    def append(self, run: Dict[str, Any]) -> str:
        if not isinstance(run, dict):
            raise TypeError("run must be a dict")
        run_id = str(run.get("id") or _new_id("gov"))
        run = {**run, "id": run_id, "persisted_at": _now_iso()}
        with self._lock:
            self._records.append(run)
            if self._max_records and len(self._records) > self._max_records:
                self._records = self._records[-self._max_records :]
            self._persist_locked()
        return run_id

    # ----- read -----------------------------------------------------------
    def get(self, run_id: str) -> Optional[Dict[str, Any]]:
        with self._lock:
            for r in reversed(self._records):
                if r.get("id") == run_id:
                    return r
        return None

    def list(
        self,
        *,
        limit: int = 50,
        succeeded: Optional[bool] = None,
    ) -> List[Dict[str, Any]]:
        with self._lock:
            rows = list(reversed(self._records))
        if succeeded is not None:
            rows = [r for r in rows if bool(r.get("succeeded")) is succeeded]
        return rows[:limit]

    def count(self) -> int:
        with self._lock:
            return len(self._records)

    def clear(self) -> None:
        with self._lock:
            self._records = []
            self._persist_locked()

    # ----- persistence ----------------------------------------------------
    def _persist_locked(self) -> None:
        if not self._persist_path:
            return
        try:
            os.makedirs(os.path.dirname(self._persist_path), exist_ok=True)
            with open(self._persist_path, "w", encoding="utf-8") as f:
                json.dump(self._records[-200:], f, ensure_ascii=False, default=str)
        except Exception:
            pass


__all__ = ["FailureKnowledgeBase", "RunHistoryStore"]