"""P6-2 P1-2: storyboard_cache_redis.py — Redis-backed storyboard cache.

The storyboard cache stores generated storyboard JSON keyed by
``(workflow_id, scene_id)``.  Multi-worker safe: all workers share the
same Redis instance so a storyboard generated by worker A is immediately
visible to worker B.

Design
------
- Primary backend: Redis (``redis-py``).
- Fallback: in-process LRU dict (single-process only — not multi-worker
  safe, but useful for unit tests and offline dev).
- TTL: 1 hour default; configurable via env ``STORYBOARD_CACHE_TTL``.
- Key format: ``storyboard:{workflow_id}:{scene_id}``.

Usage
-----
>>> from engines.storyboard_cache_redis import (
...     get_storyboard_cache, cache_storyboard, lookup_storyboard,
... )
>>> cache_storyboard("wf_001", "scene_42", {"panels": [...]})
>>> board = lookup_storyboard("wf_001", "scene_42")
>>> # board -> {"panels": [...]}

Multi-worker safety
-------------------
- ``cache_storyboard`` uses Redis ``SET`` (atomic).
- ``lookup_storyboard`` uses Redis ``GET`` (atomic).
- TTL ensures stale boards auto-expire.
- Falls back to LRU only when ``REDIS_URL`` env is unset AND ``offline``
  is explicitly True (default False in production).
"""
from __future__ import annotations

import json
import logging
import os
import threading
import time
from collections import OrderedDict
from typing import Any, Dict, Optional

logger = logging.getLogger("imdf.storyboard_cache")


# ═══════════════════════════════════════════════════════════════════════
# Configuration
# ═══════════════════════════════════════════════════════════════════════

REDIS_URL_ENV = "STORYBOARD_CACHE_REDIS_URL"
TTL_ENV = "STORYBOARD_CACHE_TTL"
MAX_ENTRIES_ENV = "STORYBOARD_CACHE_MAX_ENTRIES"

DEFAULT_TTL = 3600           # 1 hour
DEFAULT_MAX_ENTRIES = 1024
KEY_PREFIX = "storyboard"


def _redis_url() -> str:
    return os.environ.get(REDIS_URL_ENV, "").strip()


def _ttl() -> int:
    try:
        return int(os.environ.get(TTL_ENV, str(DEFAULT_TTL)))
    except ValueError:
        return DEFAULT_TTL


def _max_entries() -> int:
    try:
        return int(os.environ.get(MAX_ENTRIES_ENV, str(DEFAULT_MAX_ENTRIES)))
    except ValueError:
        return DEFAULT_MAX_ENTRIES


def make_key(workflow_id: str, scene_id: str) -> str:
    """Build the canonical Redis key for a (workflow, scene) pair."""
    return f"{KEY_PREFIX}:{workflow_id}:{scene_id}"


# ═══════════════════════════════════════════════════════════════════════
# Redis backend
# ═══════════════════════════════════════════════════════════════════════

class RedisBackend:
    """Thin Redis wrapper using redis-py.  Lazily connects on first use."""

    def __init__(self, url: str, *, default_ttl: int = DEFAULT_TTL):
        self.url = url
        self.default_ttl = default_ttl
        self._client = None
        self._init_failed = False
        self._lock = threading.Lock()
        # metrics
        self.hits = 0
        self.misses = 0
        self.sets = 0
        self.deletes = 0

    def _ensure_client(self) -> Optional[Any]:
        if self._client is not None:
            return self._client
        if self._init_failed:
            return None
        with self._lock:
            if self._client is not None:
                return self._client
            try:
                import redis  # type: ignore
                self._client = redis.Redis.from_url(
                    self.url,
                    decode_responses=False,
                    socket_connect_timeout=1.5,
                    socket_timeout=1.5,
                )
                # ping to verify connectivity
                self._client.ping()
                logger.info("storyboard_redis_connected url=%s", self.url)
            except Exception as exc:  # noqa: BLE001
                self._init_failed = True
                self._client = None
                logger.warning(
                    "storyboard_redis_init_failed url=%s err=%s",
                    self.url, exc,
                )
        return self._client

    # ---- core ops ----

    def get(self, key: str) -> Optional[Any]:
        client = self._ensure_client()
        if client is None:
            return None
        try:
            raw = client.get(key)
        except Exception as exc:  # noqa: BLE001
            logger.debug("storyboard_redis_get_failed key=%s err=%s", key, exc)
            return None
        if raw is None:
            self.misses += 1
            return None
        try:
            value = json.loads(raw)
            self.hits += 1
            return value
        except (TypeError, ValueError):
            # Corrupt cache entry — drop it
            try:
                client.delete(key)
            except Exception:
                pass
            return None

    def set(self, key: str, value: Any, ttl_seconds: Optional[int] = None) -> bool:
        client = self._ensure_client()
        if client is None:
            return False
        try:
            payload = json.dumps(value, default=str).encode("utf-8")
            ttl = int(ttl_seconds) if ttl_seconds and ttl_seconds > 0 else self.default_ttl
            client.setex(key, ttl, payload)
            self.sets += 1
            return True
        except Exception as exc:  # noqa: BLE001
            logger.debug("storyboard_redis_set_failed key=%s err=%s", key, exc)
            return False

    def delete(self, key: str) -> bool:
        client = self._ensure_client()
        if client is None:
            return False
        try:
            n = client.delete(key)
            self.deletes += 1
            return bool(n)
        except Exception as exc:  # noqa: BLE001
            logger.debug("storyboard_redis_delete_failed key=%s err=%s", key, exc)
            return False

    def clear_prefix(self, prefix: str) -> int:
        client = self._ensure_client()
        if client is None:
            return 0
        try:
            keys = list(client.scan_iter(match=f"{prefix}*"))
            if keys:
                client.delete(*keys)
                self.deletes += len(keys)
            return len(keys)
        except Exception:
            return 0

    def stats(self) -> Dict[str, Any]:
        return {
            "backend": "redis",
            "url": self.url,
            "connected": self._client is not None,
            "hits": self.hits,
            "misses": self.misses,
            "sets": self.sets,
            "deletes": self.deletes,
        }


# ═══════════════════════════════════════════════════════════════════════
# In-memory LRU fallback (single-worker only — NOT multi-worker safe)
# ═══════════════════════════════════════════════════════════════════════

class MemoryLRU:
    """Thread-safe in-memory LRU used as a fallback or for tests."""

    def __init__(self, max_entries: int = DEFAULT_MAX_ENTRIES):
        self.max_entries = max(1, max_entries)
        self._data: "OrderedDict[str, tuple[float, Any]]" = OrderedDict()
        self._lock = threading.Lock()
        self.hits = 0
        self.misses = 0
        self.sets = 0
        self.deletes = 0

    def get(self, key: str) -> Optional[Any]:
        with self._lock:
            entry = self._data.get(key)
            if entry is None:
                self.misses += 1
                return None
            expire_at, value = entry
            if expire_at > 0 and expire_at < time.time():
                del self._data[key]
                self.misses += 1
                return None
            self._data.move_to_end(key)
            self.hits += 1
            return value

    def set(self, key: str, value: Any, ttl_seconds: Optional[int] = None) -> bool:
        expire_at = (time.time() + int(ttl_seconds)) if ttl_seconds and ttl_seconds > 0 else 0
        with self._lock:
            if key in self._data:
                self._data.move_to_end(key)
            self._data[key] = (expire_at, value)
            self.sets += 1
            while len(self._data) > self.max_entries:
                self._data.popitem(last=False)
        return True

    def delete(self, key: str) -> bool:
        with self._lock:
            existed = key in self._data
            if existed:
                del self._data[key]
                self.deletes += 1
            return existed

    def clear_prefix(self, prefix: str) -> int:
        with self._lock:
            keys_to_del = [k for k in self._data if k.startswith(prefix)]
            for k in keys_to_del:
                del self._data[k]
                self.deletes += 1
            return len(keys_to_del)

    def stats(self) -> Dict[str, Any]:
        with self._lock:
            return {
                "backend": "memory",
                "size": len(self._data),
                "max_entries": self.max_entries,
                "hits": self.hits,
                "misses": self.misses,
                "sets": self.sets,
                "deletes": self.deletes,
            }


# ═══════════════════════════════════════════════════════════════════════
# Composite cache: Redis primary, memory fallback when Redis is offline
# ═══════════════════════════════════════════════════════════════════════

class StoryboardCache:
    """Multi-worker safe storyboard cache.

    Strategy:
      1. Try Redis backend first (the authoritative multi-worker store).
      2. Fall back to a local LRU when Redis is unavailable so a single
         worker can still continue in dev / CI / offline mode.
      3. ``get_or_set`` always consults the primary backend first; the
         fallback only kicks in when the primary fails.
    """

    def __init__(
        self,
        redis_url: Optional[str] = None,
        *,
        default_ttl: Optional[int] = None,
        max_entries: Optional[int] = None,
    ):
        self.default_ttl = int(default_ttl) if default_ttl else _ttl()
        self.max_entries = int(max_entries) if max_entries else _max_entries()
        self.redis = RedisBackend(
            redis_url or _redis_url(),
            default_ttl=self.default_ttl,
        )
        self.memory = MemoryLRU(max_entries=self.max_entries)

    # ---- primitive ops ----

    def get(self, key: str) -> Optional[Any]:
        v = self.redis.get(key)
        if v is not None:
            return v
        # Fallback to memory only if Redis confirmed unavailable
        if not self.redis._init_failed and self.redis._client is not None:
            return None
        return self.memory.get(key)

    def set(self, key: str, value: Any, ttl_seconds: Optional[int] = None) -> bool:
        ttl = int(ttl_seconds) if ttl_seconds and ttl_seconds > 0 else self.default_ttl
        ok_redis = self.redis.set(key, value, ttl_seconds=ttl)
        # Always write to memory too — keeps a local copy for hot reads
        self.memory.set(key, value, ttl_seconds=ttl)
        return ok_redis

    def delete(self, key: str) -> bool:
        ok = self.redis.delete(key)
        self.memory.delete(key)
        return ok

    def invalidate_workflow(self, workflow_id: str) -> int:
        prefix = f"{KEY_PREFIX}:{workflow_id}:"
        n_redis = self.redis.clear_prefix(prefix)
        n_mem = self.memory.clear_prefix(prefix)
        return max(n_redis, n_mem)

    def stats(self) -> Dict[str, Any]:
        return {
            "redis": self.redis.stats(),
            "memory": self.memory.stats(),
            "default_ttl": self.default_ttl,
        }


# ═══════════════════════════════════════════════════════════════════════
# Singleton accessor + high-level helpers
# ═══════════════════════════════════════════════════════════════════════

_cache: Optional[StoryboardCache] = None
_cache_lock = threading.Lock()


def get_storyboard_cache() -> StoryboardCache:
    """Return the process-global StoryboardCache (lazy init)."""
    global _cache
    if _cache is None:
        with _cache_lock:
            if _cache is None:
                _cache = StoryboardCache()
    return _cache


def reset_cache_for_tests() -> None:
    """Drop the singleton (test helper)."""
    global _cache
    _cache = None


def cache_storyboard(workflow_id: str, scene_id: str,
                     board: Any, ttl_seconds: Optional[int] = None) -> bool:
    """Store a storyboard under (workflow_id, scene_id)."""
    cache = get_storyboard_cache()
    key = make_key(workflow_id, scene_id)
    return cache.set(key, board, ttl_seconds=ttl_seconds)


def lookup_storyboard(workflow_id: str, scene_id: str) -> Optional[Any]:
    """Fetch a storyboard by (workflow_id, scene_id).  None if missing."""
    cache = get_storyboard_cache()
    return cache.get(make_key(workflow_id, scene_id))


def invalidate_workflow(workflow_id: str) -> int:
    """Drop all storyboards for a workflow (e.g. after a re-render)."""
    cache = get_storyboard_cache()
    return cache.invalidate_workflow(workflow_id)


# ═══════════════════════════════════════════════════════════════════════
# Multi-worker safety self-check
# ═══════════════════════════════════════════════════════════════════════

def self_check() -> Dict[str, Any]:
    """Quick health-check used by readiness probes.

    Returns a dict with backend status + a sample write/read cycle.
    Never raises — failures are reported in the dict.
    """
    cache = get_storyboard_cache()
    out: Dict[str, Any] = {"stats": cache.stats()}
    try:
        probe_key = make_key("__self_check__", f"probe_{int(time.time())}")
        ok_set = cache.set(probe_key, {"ts": time.time()}, ttl_seconds=5)
        out["write_ok"] = ok_set
        out["read_back"] = cache.get(probe_key)
        cache.delete(probe_key)
    except Exception as exc:  # noqa: BLE001
        out["error"] = str(exc)
    return out


__all__ = [
    "StoryboardCache",
    "RedisBackend",
    "MemoryLRU",
    "make_key",
    "get_storyboard_cache",
    "reset_cache_for_tests",
    "cache_storyboard",
    "lookup_storyboard",
    "invalidate_workflow",
    "self_check",
    "KEY_PREFIX",
    "DEFAULT_TTL",
]