apiVersion: v1
kind: Service
metadata:
  name: {{ include "nanobot-factory.fullname" . }}
  namespace: {{ .Values.namespace.name | default (include "nanobot-factory.fullname" .) }}
  labels:
    {{- include "nanobot-factory.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      appProtocol: http
    - name: backend
      port: {{ .Values.service.backendPort }}
      targetPort: backend
      protocol: TCP
      appProtocol: http
  selector:
    {{- include "nanobot-factory.selectorLabels" . | nindent 4 }}