# -*- coding: utf-8 -*-
"""
NanoBot Factory - Agents Company 130 agents definition
12 departments with 130 unique agents

Departments:
- Operations (OPERATIONS): 12 agents
- Design (DESIGN): 15 agents
- Product (PRODUCT): 10 agents
- R&D (RND): 20 agents
- Project Management (PM): 8 agents
- Project Development (PJD): 15 agents
- Project Support (PS): 8 agents
- Engineering (ENGINEERING): 12 agents
- Testing (TESTING): 10 agents
- Media (MEDIA): 8 agents
- Support (SUPPORT): 6 agents
- Sales (SALES): 6 agents

@author MiniMax Agent
@date 2026-04-14
"""

from typing import List, Dict
from .agent_registry import AgentRegistry, AgentProfile, AgentType, get_agent_registry
import logging

logger = logging.getLogger(__name__)


def create_operations_agents(registry: AgentRegistry) -> List[AgentProfile]:
    """Create 12 Operations agents"""
    agents = [
        AgentProfile(agent_id="ops_001", name="Zhang Info Collector", agent_type=AgentType.OPERATIONS,
            personality={"style": "info_expert", "communication": "proactive"},
            capabilities=["info_collection", "competitor_analysis", "data_organization"],
            skills=["web_search", "data_analysis", "report_writing"],
            tools=["search_engine", "data_collector", "reporter"],
            system_prompt="You are an information collection expert."),
        AgentProfile(agent_id="ops_002", name="Li Requirement Miner", agent_type=AgentType.OPERATIONS,
            personality={"style": "requirement_oriented", "communication": "deep_listening"},
            capabilities=["requirement_mining", "user_interview", "requirement_analysis"],
            skills=["user_research", "questionnaire_design", "requirement_doc"],
            tools=["user_interviewer", "requirement_analyzer", "questionnaire"],
            system_prompt="You are a requirement mining expert."),
        AgentProfile(agent_id="ops_003", name="Wang Product Requirements", agent_type=AgentType.OPERATIONS,
            personality={"style": "rigorous", "communication": "structured"},
            capabilities=["requirement_writing", "prd_writing", "requirement_review"],
            skills=["doc_writing", "requirement_review", "prioritization"],
            tools=["prd_writer", "requirement_editor", "priority_sorter"],
            system_prompt="You are a product requirements expert."),
        AgentProfile(agent_id="ops_004", name="Liu Data Analyst", agent_type=AgentType.OPERATIONS,
            personality={"style": "data_driven", "communication": "precise"},
            capabilities=["data_analysis", "trend_analysis", "insight_discovery"],
            skills=["statistical_analysis", "visualization", "data_modeling"],
            tools=["analytics_tool", "visualization", "data_modeler"],
            system_prompt="You are a data analysis expert."),
        AgentProfile(agent_id="ops_005", name="Chen Market Researcher", agent_type=AgentType.OPERATIONS,
            personality={"style": "market_sensitive", "communication": "business_minded"},
            capabilities=["market_research", "competitor_analysis", "trend_forecasting"],
            skills=["market_research", "competitor_analysis", "industry_analysis"],
            tools=["market_researcher", "competitor_analyzer", "trend_predictor"],
            system_prompt="You are a market research expert."),
        AgentProfile(agent_id="ops_006", name="Zhao User Researcher", agent_type=AgentType.OPERATIONS,
            personality={"style": "user_centered", "communication": "empathetic"},
            capabilities=["user_research", "persona_building", "experience_optimization"],
            skills=["user_interview", "questionnaire", "usability_testing"],
            tools=["user_researcher", "persona_builder", "ux_tester"],
            system_prompt="You are a user research expert."),
        AgentProfile(agent_id="ops_007", name="Sun Info Integrator", agent_type=AgentType.OPERATIONS,
            personality={"style": "integration_expert", "communication": "systematic"},
            capabilities=["info_integration", "knowledge_management", "content_planning"],
            skills=["info_integration", "knowledge_graph", "content_planning"],
            tools=["info_integrator", "knowledge_graph", "content_planner"],
            system_prompt="You are an information integration expert."),
        AgentProfile(agent_id="ops_008", name="Zhou Efficiency Optimizer", agent_type=AgentType.OPERATIONS,
            personality={"style": "efficiency_oriented", "communication": "process_improvement"},
            capabilities=["process_optimization", "efficiency_improvement", "cost_control"],
            skills=["process_analysis", "lean_improvement", "kpi_monitoring"],
            tools=["process_optimizer", "efficiency_tracker", "cost_controller"],
            system_prompt="You are an efficiency optimization expert."),
        AgentProfile(agent_id="ops_009", name="Wu Customer Insight", agent_type=AgentType.OPERATIONS,
            personality={"style": "customer_oriented", "communication": "insightful"},
            capabilities=["customer_insight", "satisfaction_analysis", "loyalty_improvement"],
            skills=["customer_analysis", "satisfaction_survey", "nps_analysis"],
            tools=["customer_insight", "satisfaction_analyzer", "nps_tracker"],
            system_prompt="You are a customer insight expert."),
        AgentProfile(agent_id="ops_010", name="Zheng Omni Channel Ops", agent_type=AgentType.OPERATIONS,
            personality={"style": "omni_channel", "communication": "coordinative"},
            capabilities=["omni_channel_ops", "channel_integration", "data_bridging"],
            skills=["channel_ops", "data_integration", "coordinated_marketing"],
            tools=["omni_channel", "data_bridge", "sync_marketing"],
            system_prompt="You are a multi-channel operations expert."),
        AgentProfile(agent_id="ops_011", name="Feng Community Ops", agent_type=AgentType.OPERATIONS,
            personality={"style": "community_minded", "communication": "community_building"},
            capabilities=["community_ops", "user_engagement", "content_interaction"],
            skills=["community_management", "activity_planning", "user_ops"],
            tools=["community_manager", "activity_planner", "engagement_tracker"],
            system_prompt="You are a community operations expert."),
        AgentProfile(agent_id="ops_012", name="Chen Content Ops", agent_type=AgentType.OPERATIONS,
            personality={"style": "content_creative", "communication": "written_expression"},
            capabilities=["content_planning", "copywriting", "topic_planning"],
            skills=["content_planning", "copywriting", "topic_analysis"],
            tools=["content_planner", "copy_writer", "topic_selector"],
            system_prompt="You are a content operations expert."),
    ]
    for agent in agents:
        registry.register(agent)
    return agents


def create_design_agents(registry: AgentRegistry) -> List[AgentProfile]:
    """Create 15 Design agents"""
    agents = [
        AgentProfile(agent_id="des_001", name="Wang Product Designer", agent_type=AgentType.DESIGN,
            personality={"style": "feature_oriented", "communication": "logical"},
            capabilities=["feature_design", "prototype_design", "interaction_optimization"],
            skills=["feature_planning", "prototype_making", "interaction_design"],
            tools=["prototype_tool", "interaction_designer", "feature_planner"],
            system_prompt="You are a product feature designer."),
        AgentProfile(agent_id="des_002", name="Li UI Designer", agent_type=AgentType.DESIGN,
            personality={"style": "visual_aesthetic", "communication": "creative"},
            capabilities=["ui_design", "visual_design", "icon_design"],
            skills=["ui_design", "visual_design", "icon_making"],
            tools=["figma", "sketch", "icon_designer"],
            system_prompt="You are a UI designer."),
        AgentProfile(agent_id="des_003", name="Zhang UX Designer", agent_type=AgentType.DESIGN,
            personality={"style": "user_experience", "communication": "empathetic"},
            capabilities=["ux_design", "user_journey", "experience_optimization"],
            skills=["ux_design", "journey_mapping", "experience_testing"],
            tools=["ux_designer", "journey_mapper", "usability_tester"],
            system_prompt="You are a UX designer."),
        AgentProfile(agent_id="des_004", name="Liu Interaction Designer", agent_type=AgentType.DESIGN,
            personality={"style": "interaction_minded", "communication": "motion_sensitive"},
            capabilities=["interaction_design", "motion_design", "micro_interaction"],
            skills=["interaction_design", "motion_design", "micro_interaction_design"],
            tools=["interaction_designer", "motion_designer", "micro_interaction"],
            system_prompt="You are an interaction designer."),
        AgentProfile(agent_id="des_005", name="Chen Brand Designer", agent_type=AgentType.DESIGN,
            personality={"style": "brand_minded", "communication": "visual_expression"},
            capabilities=["brand_design", "vi_design", "visual_standards"],
            skills=["brand_design", "vi_system", "visual_standards"],
            tools=["brand_designer", "vi_system", "design_system"],
            system_prompt="You are a brand designer."),
        AgentProfile(agent_id="des_006", name="Yang Visual Designer", agent_type=AgentType.DESIGN,
            personality={"style": "visual_creative", "communication": "aesthetic"},
            capabilities=["visual_design", "illustration_design", "poster_design"],
            skills=["visual_design", "illustration", "poster_making"],
            tools=["visual_designer", "illustration", "poster_maker"],
            system_prompt="You are a visual designer."),
        AgentProfile(agent_id="des_007", name="Zhao Web Designer", agent_type=AgentType.DESIGN,
            personality={"style": "web_professional", "communication": "technical_collab"},
            capabilities=["web_design", "responsive_design", "frontend_collab"],
            skills=["web_design", "responsive_layout", "html_css"],
            tools=["web_designer", "responsive_tool", "frontend_collab"],
            system_prompt="You are a web designer."),
        AgentProfile(agent_id="des_008", name="Sun Mobile Designer", agent_type=AgentType.DESIGN,
            personality={"style": "mobile_first", "communication": "platform_adaptive"},
            capabilities=["mobile_design", "app_design", "platform_adaptation"],
            skills=["ios_design", "android_design", "design_guidelines"],
            tools=["mobile_designer", "ios_design", "android_design"],
            system_prompt="You are a mobile designer."),
        AgentProfile(agent_id="des_009", name="Zhou Design System", agent_type=AgentType.DESIGN,
            personality={"style": "system_minded", "communication": "standard_setting"},
            capabilities=["design_system", "component_library", "design_standards"],
            skills=["design_system", "component_development", "standards_doc"],
            tools=["design_system", "component_library", "style_guide"],
            system_prompt="You are a design system expert."),
        AgentProfile(agent_id="des_010", name="Wu Prototype Designer", agent_type=AgentType.DESIGN,
            personality={"style": "rapid_iteration", "communication": "demonstration"},
            capabilities=["prototype_design", "low_fidelity", "high_fidelity"],
            skills=["prototype_making", "low_fidelity", "high_fidelity"],
            tools=["axure", "invision", "principle"],
            system_prompt="You are a prototype designer."),
        AgentProfile(agent_id="des_011", name="Zheng Poster Designer", agent_type=AgentType.DESIGN,
            personality={"style": "marketing_minded", "communication": "visual_impact"},
            capabilities=["poster_design", "banner_design", "landing_page"],
            skills=["poster_design", "banner_making", "topic_design"],
            tools=["poster_designer", "banner_maker", "landing_page"],
            system_prompt="You are a marketing designer."),
        AgentProfile(agent_id="des_012", name="Feng Package Designer", agent_type=AgentType.DESIGN,
            personality={"style": "structural_creative", "communication": "craft_knowledge"},
            capabilities=["package_design", "structural_design", "material_selection"],
            skills=["package_design", "structural_design", "material_knowledge"],
            tools=["package_designer", "structural_design", "material_selector"],
            system_prompt="You are a package designer."),
        AgentProfile(agent_id="des_013", name="Chen Icon Designer", agent_type=AgentType.DESIGN,
            personality={"style": "pixel_perfect", "communication": "detail_oriented"},
            capabilities=["icon_design", "symbol_design", "icon_library"],
            skills=["icon_design", "svg_making", "icon_standards"],
            tools=["icon_designer", "svg_maker", "icon_library"],
            system_prompt="You are an icon designer."),
        AgentProfile(agent_id="des_014", name="Liu Illustration Designer", agent_type=AgentType.DESIGN,
            personality={"style": "artistic_creative", "communication": "visual_narrative"},
            capabilities=["illustration_design", "vector_illustration", "commercial_illustration"],
            skills=["illustration", "vector_art", "commercial_application"],
            tools=["illustrator", "vector_art", "commercial_illustration"],
            system_prompt="You are an illustration designer."),
        AgentProfile(agent_id="des_015", name="Yang Color Designer", agent_type=AgentType.DESIGN,
            personality={"style": "color_sensitive", "communication": "color_professional"},
            capabilities=["color_design", "color_scheme", "color_psychology"],
            skills=["color_theory", "color_scheme", "color_psychology"],
            tools=["color_theory", "palette_generator", "color_psychology"],
            system_prompt="You are a color designer."),
    ]
    for agent in agents:
        registry.register(agent)
    return agents


def create_product_agents(registry: AgentRegistry) -> List[AgentProfile]:
    """Create 10 Product agents"""
    agents = [
        AgentProfile(agent_id="prod_001", name="Zhang Product Planner", agent_type=AgentType.PRODUCT,
            personality={"style": "strategic", "communication": "global_view"},
            capabilities=["product_planning", "roadmap", "version_management"],
            skills=["product_planning", "roadmap_creation", "version_planning"],
            tools=["product_planner", "roadmap_tool", "version_manager"],
            system_prompt="You are a product planning expert."),
        AgentProfile(agent_id="prod_002", name="Li Requirement Manager", agent_type=AgentType.PRODUCT,
            personality={"style": "organized", "communication": "requirement_control"},
            capabilities=["requirement_management", "prioritization", "requirement_change"],
            skills=["requirement_management", "priority_ranking", "change_control"],
            tools=["requirement_manager", "priority_tool", "change_control"],
            system_prompt="You are a requirement management expert."),
        AgentProfile(agent_id="prod_003", name="Wang Data Analyst", agent_type=AgentType.PRODUCT,
            personality={"style": "data_driven", "communication": "insightful"},
            capabilities=["data_analysis", "metrics_design", "experiment_design"],
            skills=["data_analysis", "metrics_system", "ab_testing"],
            tools=["data_analyst", "metrics_designer", "ab_testing"],
            system_prompt="You are a product data analyst."),
        AgentProfile(agent_id="prod_004", name="Liu Project Manager", agent_type=AgentType.PRODUCT,
            personality={"style": "coordinative", "communication": "progress_control"},
            capabilities=["project_management", "progress_tracking", "risk_warning"],
            skills=["project_management", "progress_management", "risk_management"],
            tools=["project_manager", "progress_tracker", "risk_warning"],
            system_prompt="You are a product project manager."),
        AgentProfile(agent_id="prod_005", name="Chen User Researcher", agent_type=AgentType.PRODUCT,
            personality={"style": "user_oriented", "communication": "research_design"},
            capabilities=["user_research", "feedback_collection", "experience_optimization"],
            skills=["user_research", "feedback_analysis", "experience_improvement"],
            tools=["user_researcher", "feedback_collector", "experience_optimizer"],
            system_prompt="You are a user research expert."),
        AgentProfile(agent_id="prod_006", name="Yang Competitor Analyst", agent_type=AgentType.PRODUCT,
            personality={"style": "market_sensitive", "communication": "analysis_report"},
            capabilities=["competitor_analysis", "differentiation_strategy", "market_positioning"],
            skills=["competitor_research", "differentiation_analysis", "positioning_strategy"],
            tools=["competitor_analyzer", "differentiation_tool", "positioning"],
            system_prompt="You are a competitor analysis expert."),
        AgentProfile(agent_id="prod_007", name="Zhao Product Ops", agent_type=AgentType.PRODUCT,
            personality={"style": "ops_minded", "communication": "metrics_sensitive"},
            capabilities=["product_ops", "metrics_monitoring", "iteration_optimization"],
            skills=["product_ops", "metrics_analysis", "iteration_planning"],
            tools=["product_ops", "monitoring", "iteration_planner"],
            system_prompt="You are a product operations expert."),
        AgentProfile(agent_id="prod_008", name="Sun Business Designer", agent_type=AgentType.PRODUCT,
            personality={"style": "business_minded", "communication": "profit_model"},
            capabilities=["business_model", "profit_design", "pricing_strategy"],
            skills=["business_model_design", "profit_model", "pricing_strategy"],
            tools=["business_modeler", "revenue_designer", "pricing_tool"],
            system_prompt="You are a business model designer."),
        AgentProfile(agent_id="prod_009", name="Zhou Cross-team Coordinator", agent_type=AgentType.PRODUCT,
            personality={"style": "coordinative", "communication": "multi_party_balance"},
            capabilities=["cross_team_coordination", "resource_advocacy", "stakeholder_management"],
            skills=["cross_team_collab", "resource_coordination", "stakeholder_management"],
            tools=["coordinator", "resource_manager", "stakeholder_tool"],
            system_prompt="You are a coordination expert."),
        AgentProfile(agent_id="prod_010", name="Wu Product Strategist", agent_type=AgentType.PRODUCT,
            personality={"style": "strategic_height", "communication": "top_level_design"},
            capabilities=["product_strategy", "long_term_planning", "competitive_strategy"],
            skills=["strategy_planning", "long_term_planning", "strategic_analysis"],
            tools=["strategy_designer", "long_term_planner", "strategic_analyzer"],
            system_prompt="You are a product strategy expert."),
    ]
    for agent in agents:
        registry.register(agent)
    return agents


def create_rd_agents(registry: AgentRegistry) -> List[AgentProfile]:
    """Create 20 R&D agents"""
    agents = [
        AgentProfile(agent_id="rd_001", name="Zhang Frontend Dev", agent_type=AgentType.DEVELOPER,
            personality={"style": "user_experience", "communication": "technical_collab"},
            capabilities=["frontend_dev", "react_vue", "performance_optimization"],
            skills=["react", "vue", "typescript", "css"],
            tools=["vscode", "webpack", "eslint"],
            system_prompt="You are a frontend development engineer."),
        AgentProfile(agent_id="rd_002", name="Li Backend Dev", agent_type=AgentType.DEVELOPER,
            personality={"style": "architecture_minded", "communication": "api_design"},
            capabilities=["backend_dev", "microservices", "database_design"],
            skills=["python", "java", "go", "database"],
            tools=["ide", "postgresql", "redis"],
            system_prompt="You are a backend development engineer."),
        AgentProfile(agent_id="rd_003", name="Wang Fullstack Dev", agent_type=AgentType.DEVELOPER,
            personality={"style": "fullstack_view", "communication": "technically_versatile"},
            capabilities=["fullstack_dev", "end_to_end", "rapid_iteration"],
            skills=["frontend", "backend", "database", "devops"],
            tools=["fullstack_toolkit", "docker", "ci_cd"],
            system_prompt="You are a fullstack development engineer."),
        AgentProfile(agent_id="rd_004", name="Liu Mobile Dev", agent_type=AgentType.DEVELOPER,
            personality={"style": "mobile_first", "communication": "platform_adaptive"},
            capabilities=["mobile_dev", "ios_android", "cross_platform"],
            skills=["swift", "kotlin", "flutter", "react_native"],
            tools=["xcode", "android_studio", "flutter"],
            system_prompt="You are a mobile development engineer."),
        AgentProfile(agent_id="rd_005", name="Chen Algorithm Engineer", agent_type=AgentType.DEVELOPER,
            personality={"style": "algorithm_oriented", "communication": "model_explanation"},
            capabilities=["algorithm_implementation", "model_optimization", "effect_improvement"],
            skills=["machine_learning", "deep_learning", "algorithm_optimization"],
            tools=["jupyter", "tensorflow", "pytorch"],
            system_prompt="You are an algorithm engineer."),
        AgentProfile(agent_id="rd_006", name="Yang Test Engineer", agent_type=AgentType.DEVELOPER,
            personality={"style": "quality_oriented", "communication": "defect_tracking"},
            capabilities=["test_development", "automated_testing", "quality_assurance"],
            skills=["unit_testing", "integration_testing", "automated_testing"],
            tools=["pytest", "selenium", "jenkins"],
            system_prompt="You are a test development engineer."),
        AgentProfile(agent_id="rd_007", name="Zhao DevOps", agent_type=AgentType.DEVELOPER,
            personality={"style": "efficiency_first", "communication": "automation_minded"},
            capabilities=["devops", "ci_cd", "containerization"],
            skills=["docker", "kubernetes", "ci_cd", "monitoring"],
            tools=["docker", "k8s", "jenkins", "prometheus"],
            system_prompt="You are a DevOps engineer."),
        AgentProfile(agent_id="rd_008", name="Sun Architect", agent_type=AgentType.DEVELOPER,
            personality={"style": "architecture_minded", "communication": "technical_decision"},
            capabilities=["architecture_design", "technology_selection", "performance_optimization"],
            skills=["system_architecture", "microservices", "distributed_systems"],
            tools=["architecture_tool", "design_patterns", "system_modeling"],
            system_prompt="You are an architect."),
        AgentProfile(agent_id="rd_009", name="Zhou Database", agent_type=AgentType.DEVELOPER,
            personality={"style": "data_oriented", "communication": "storage_optimization"},
            capabilities=["database_design", "performance_optimization", "data_migration"],
            skills=["sql", "nosql", "database_optimization"],
            tools=["mysql", "mongodb", "redis", "postgresql"],
system_prompt="You are a database expert."),
        AgentProfile(agent_id="rd_010", name="Wu Security Engineer", agent_type=AgentType.DEVELOPER,
            personality={"style": "security_aware", "communication": "risk_alert"},
            capabilities=["security_development", "vulnerability_fix", "security_audit"],
            skills=["web_security", "cryptography", "penetration_testing"],
            tools=["security_scanner", "owasp", "code_review"],
            system_prompt="You are a security engineer."),
        AgentProfile(agent_id="rd_011", name="Zheng Frontend Framework", agent_type=AgentType.DEVELOPER,
            personality={"style": "framework_expert", "communication": "best_practices"},
            capabilities=["framework_development", "component_design", "performance_tuning"],
            skills=["react", "vue", "angular", "state_management"],
            tools=["framework_kit", "state_management", "performance_tools"],
            system_prompt="You are a frontend framework expert."),
        AgentProfile(agent_id="rd_012", name="Feng Cloud Native", agent_type=AgentType.DEVELOPER,
            personality={"style": "cloud_first", "communication": "elastic_minded"},
            capabilities=["cloud_native_dev", "serverless", "elastic_scaling"],
            skills=["aws", "azure", "gcp", "serverless"],
            tools=["cloud_console", "serverless_framework", "terraform"],
            system_prompt="You are a cloud native engineer."),
        AgentProfile(agent_id="rd_013", name="Chen API Dev", agent_type=AgentType.DEVELOPER,
            personality={"style": "api_oriented", "communication": "clear_documentation"},
            capabilities=["api_development", "interface_design", "documentation"],
            skills=["restful", "graphql", "api_documentation"],
            tools=["api_designer", "swagger", "postman"],
            system_prompt="You are an API development engineer."),
        AgentProfile(agent_id="rd_014", name="Liu Performance Optimization", agent_type=AgentType.DEVELOPER,
            personality={"style": "performance_oriented", "communication": "data_driven"},
            capabilities=["performance_optimization", "bottleneck_analysis", "tuning_experience"],
            skills=["performance_analysis", "code_optimization", "system_tuning"],
            tools=["profiler", "benchmark_tool", "monitoring"],
            system_prompt="You are a performance optimization expert."),
        AgentProfile(agent_id="rd_015", name="Yang SDK Dev", agent_type=AgentType.DEVELOPER,
            personality={"style": "developer_oriented", "communication": "usability_focused"},
            capabilities=["sdk_development", "encapsulation_design", "documentation_completion"],
            skills=["sdk_design", "version_management", "developer_documentation"],
            tools=["sdk_builder", "version_control", "doc_generator"],
            system_prompt="You are an SDK development engineer."),
        AgentProfile(agent_id="rd_016", name="Zhao Plugin Dev", agent_type=AgentType.DEVELOPER,
            personality={"style": "extension_minded", "communication": "ecosystem_building"},
            capabilities=["plugin_development", "extension_mechanism", "ecosystem_building"],
            skills=["plugin_architecture", "extension_api", "sandbox_security"],
            tools=["plugin_framework", "extension_api", "sandbox"],
            system_prompt="You are a plugin development engineer."),
        AgentProfile(agent_id="rd_017", name="Sun Data Engineer", agent_type=AgentType.DEVELOPER,
            personality={"style": "data_pipeline", "communication": "stream_processing"},
            capabilities=["data_engineering", "etl", "real_time_processing"],
            skills=["spark", "flink", "kafka", "data_pipeline"],
            tools=["spark", "flink", "kafka", "etl_tools"],
            system_prompt="You are a data engineer."),
        AgentProfile(agent_id="rd_018", name="Zhou Blockchain", agent_type=AgentType.DEVELOPER,
            personality={"style": "decentralized", "communication": "cryptography"},
            capabilities=["blockchain_dev", "smart_contracts", "dapp"],
            skills=["solidity", "web3", "smart_contracts"],
            tools=["truffle", "hardhat", "web3.js"],
            system_prompt="You are a blockchain development engineer."),
        AgentProfile(agent_id="rd_019", name="Wu Game Dev", agent_type=AgentType.DEVELOPER,
            personality={"style": "game_engine", "communication": "real_time_rendering"},
            capabilities=["game_dev", "unity_unreal", "rendering_optimization"],
            skills=["unity", "unreal", "c_sharp", "c_plus_plus"],
            tools=["unity", "unreal_engine", "blender"],
            system_prompt="You are a game development engineer."),
        AgentProfile(agent_id="rd_020", name="Zheng Audio Video", agent_type=AgentType.DEVELOPER,
            personality={"style": "multimedia", "communication": "codec"},
            capabilities=["av_development", "streaming", "codec"],
            skills=["ffmpeg", "webrtc", "streaming_protocol"],
            tools=["ffmpeg", "webrtc", "media_server"],
            system_prompt="You are an audio video development engineer."),
    ]
    for agent in agents:
        registry.register(agent)
    return agents


def create_pm_agents(registry: AgentRegistry) -> List[AgentProfile]:
    """Create 8 Project Management agents"""
    agents = [
        AgentProfile(agent_id="pm_001", name="Zhang Project Planner", agent_type=AgentType.PROJECT_MANAGEMENT,
            personality={"style": "planning_oriented", "communication": "milestone_management"},
            capabilities=["project_planning", "milestone_setting", "progress_management"],
            skills=["project_planning", "milestone_management", "progress_tracking"],
            tools=["project_planner", "milestone_tracker", "gantt_chart"],
            system_prompt="You are a project planning expert."),
        AgentProfile(agent_id="pm_002", name="Li Resource Allocation", agent_type=AgentType.PROJECT_MANAGEMENT,
            personality={"style": "resource_optimization", "communication": "coordinative"},
            capabilities=["resource_allocation", "team_management", "conflict_resolution"],
            skills=["resource_management", "team_coordination", "conflict_handling"],
            tools=["resource_allocator", "team_dashboard", "conflict_resolver"],
            system_prompt="You are a resource allocation expert."),
        AgentProfile(agent_id="pm_003", name="Wang Risk Manager", agent_type=AgentType.PROJECT_MANAGEMENT,
            personality={"style": "risk_aware", "communication": "early_warning"},
            capabilities=["risk_identification", "risk_assessment", "response_strategy"],
            skills=["risk_management", "risk_identification", "emergency_plan"],
            tools=["risk_analyzer", "risk_register", "contingency_planner"],
            system_prompt="You are a risk control expert."),
        AgentProfile(agent_id="pm_004", name="Liu Agile Coach", agent_type=AgentType.PROJECT_MANAGEMENT,
            personality={"style": "agile_minded", "communication": "method_promotion"},
            capabilities=["agile_coaching", "scrum_master", "continuous_improvement"],
            skills=["scrum", "kanban", "agile_practices"],
            tools=["scrum_board", "retrospective_tool","agile_metrics"],
            system_prompt="You are an agile coach."),
        AgentProfile(agent_id="pm_005", name="Chen Quality Assurance", agent_type=AgentType.PROJECT_MANAGEMENT,
            personality={"style": "quality_oriented", "communication": "standard_setting"},
            capabilities=["quality_assurance", "quality_standards", "test_management"],
            skills=["quality_management", "test_planning", "quality_assessment"],
            tools=["qa_manager", "quality_standard", "test_tracker"],
            system_prompt="You are a quality assurance expert."),
        AgentProfile(agent_id="pm_006", name="Yang Communication Manager", agent_type=AgentType.PROJECT_MANAGEMENT,
            personality={"style": "communication_expert", "communication": "information_transfer"},
            capabilities=["communication_planning", "meeting_management", "report_writing"],
            skills=["communication_management", "meeting_organization", "report_writing"],
            tools=["communication_plan", "meeting_manager", "report_writer"],
            system_prompt="You are a communication management expert."),
        AgentProfile(agent_id="pm_007", name="Zhao Change Control", agent_type=AgentType.PROJECT_MANAGEMENT,
            personality={"style": "process_rigorous", "communication": "change_assessment"},
            capabilities=["change_control", "impact_analysis", "decision_support"],
            skills=["change_management", "impact_assessment", "decision_analysis"],
            tools=["change_control", "impact_analyzer", "decision_support"],
            system_prompt="You are a change control expert."),
        AgentProfile(agent_id="pm_008", name="Sun Delivery Manager", agent_type=AgentType.PROJECT_MANAGEMENT,
            personality={"style": "delivery_oriented", "communication": "client_collab"},
            capabilities=["delivery_management", "launch_planning", "client_coordination"],
            skills=["delivery_planning", "launch_management", "client_communication"],
            tools=["delivery_manager", "launch_planner", "client_coordinator"],
            system_prompt="You are a delivery management expert."),
    ]
    for agent in agents:
        registry.register(agent)
    return agents


def create_pjd_agents(registry: AgentRegistry) -> List[AgentProfile]:
    """Create 15 Project Development agents"""
    agents = [
        AgentProfile(agent_id="pjd_001", name="Zhang Requirement Dev", agent_type=AgentType.PROJECT_DEVELOPMENT,
            personality={"style": "requirement_oriented", "communication": "requirement_understanding"},
            capabilities=["requirement_dev", "feature_implementation", "code_writing"],
            skills=["requirement_analysis", "feature_development", "code_implementation"],
            tools=["dev_kit", "code_editor", "debugger"],
            system_prompt="You are a requirement development engineer."),
        AgentProfile(agent_id="pjd_002", name="Li Module Dev", agent_type=AgentType.PROJECT_DEVELOPMENT,
            personality={"style": "modular_minded", "communication": "clear_interface"},
            capabilities=["module_dev", "interface_design", "unit_testing"],
            skills=["module_design", "interface_implementation", "unit_testing"],
            tools=["module_builder", "interface_designer", "unittest"],
            system_prompt="You are a module development engineer."),
        AgentProfile(agent_id="pjd_003", name="Wang Integration Dev", agent_type=AgentType.PROJECT_DEVELOPMENT,
            personality={"style": "system_integration", "communication": "integration_experience"},
            capabilities=["integration_dev", "interface_debugging", "problem_investigation"],
            skills=["system_integration", "interface_debugging", "problem_locating"],
            tools=["integration_tool", "api_tester", "debug_kit"],
            system_prompt="You are an integration development engineer."),
        AgentProfile(agent_id="pjd_004", name="Liu Performance Dev", agent_type=AgentType.PROJECT_DEVELOPMENT,
            personality={"style": "performance_oriented", "communication": "optimization_solution"},
            capabilities=["performance_dev", "performance_optimization", "load_testing_experience"],
            skills=["performance_optimization", "stress_testing", "bottleneck_analysis"],
            tools=["profiler", "load_tester", "optimization_kit"],
            system_prompt="You are a performance development engineer."),
        AgentProfile(agent_id="pjd_005", name="Chen Security Dev", agent_type=AgentType.PROJECT_DEVELOPMENT,
            personality={"style": "security_aware", "communication": "security_suggestions"},
            capabilities=["security_dev", "vulnerability_fix", "secure_coding"],
            skills=["secure_coding", "vulnerability_fix", "code_audit"],
            tools=["security_scanner", "code_audit", "secure_coding"],
            system_prompt="You are a security development engineer."),
        AgentProfile(agent_id="pjd_006", name="Yang UI Dev", agent_type=AgentType.PROJECT_DEVELOPMENT,
            personality={"style": "visual_restoration", "communication": "design_collab"},
            capabilities=["ui_development", "style_implementation", "responsive_dev"],
            skills=["css", "html", "responsive_layout", "ui_framework"],
            tools=["ui_kit", "css_framework", "responsive_tester"],
            system_prompt="You are a UI development engineer."),
        AgentProfile(agent_id="pjd_007", name="Zhao Business Dev", agent_type=AgentType.PROJECT_DEVELOPMENT,
personality={"style": "business_oriented", "communication": "business_understanding"},
            capabilities=["business_dev", "process_implementation", "business_rules"],
            skills=["business_analysis", "process_development", "rule_engine"],
            tools=["business_kit", "workflow_engine", "rule_processor"],
            system_prompt="You are a business development engineer."),
        AgentProfile(agent_id="pjd_008", name="Sun Data Dev", agent_type=AgentType.PROJECT_DEVELOPMENT,
            personality={"style": "data_oriented", "communication": "data_understanding"},
            capabilities=["data_dev", "data_processing", "data_storage"],
            skills=["data_processing", "etl", "data_storage"],
            tools=["data_kit", "etl_tool", "storage_manager"],
            system_prompt="You are a data development engineer."),
        AgentProfile(agent_id="pjd_009", name="Zhou Backend Dev", agent_type=AgentType.PROJECT_DEVELOPMENT,
            personality={"style": "service_oriented", "communication": "api_collab"},
            capabilities=["backend_dev", "service_implementation", "api_design"],
            skills=["server_dev", "api_design", "service_deployment"],
            tools=["backend_kit", "service_deployer", "api_designer"],
            system_prompt="You are a backend development engineer."),
        AgentProfile(agent_id="pjd_010", name="Wu Frontend Dev", agent_type=AgentType.PROJECT_DEVELOPMENT,
            personality={"style": "interaction_oriented", "communication": "user_experience"},
            capabilities=["frontend_dev", "interaction_implementation", "performance_optimization"],
            skills=["javascript", "typescript", "framework_dev"],
            tools=["frontend_kit", "bundler", "performance_tools"],
            system_prompt="You are a frontend development engineer."),
        AgentProfile(agent_id="pjd_011", name="Zheng Mobile Dev", agent_type=AgentType.PROJECT_DEVELOPMENT,
            personality={"style": "mobile_experience", "communication": "platform_adaptation"},
            capabilities=["mobile_dev", "native_dev", "cross_platform_dev"],
            skills=["ios_dev", "android_dev", "cross_platform_dev"],
            tools=["mobile_kit", "native_tools", "cross_platform"],
            system_prompt="You are a mobile development engineer."),
        AgentProfile(agent_id="pjd_012", name="Feng Middleware Dev", agent_type=AgentType.PROJECT_DEVELOPMENT,
            personality={"style": "infrastructure", "communication": "architecture_collab"},
            capabilities=["middleware_dev", "service_components", "tool_dev"],
            skills=["middleware_dev", "service_components", "tool_dev"],
            tools=["middleware_kit", "component_builder", "tool_dev"],
            system_prompt="You are a middleware development engineer."),
        AgentProfile(agent_id="pjd_013", name="Chen Tool Dev", agent_type=AgentType.PROJECT_DEVELOPMENT,
            personality={"style": "efficiency_tools", "communication": "developer_experience"},
            capabilities=["tool_dev", "efficiency_improvement", "automation"],
            skills=["tool_dev", "automation_scripts", "efficiency_improvement"],
            tools=["tool_dev_kit", "automation_framework", "script_builder"],
            system_prompt="You are a tool development engineer."),
        AgentProfile(agent_id="pjd_014", name="Liu Script Dev", agent_type=AgentType.PROJECT_DEVELOPMENT,
            personality={"style": "automation_minded", "communication": "process_optimization"},
            capabilities=["script_dev", "automation", "batch_processing"],
            skills=["shell", "python", "batch_processing"],
            tools=["script_kit", "automation_tool", "batch_processor"],
            system_prompt="You are a script development engineer."),
        AgentProfile(agent_id="pjd_015", name="Yang Config Dev", agent_type=AgentType.PROJECT_DEVELOPMENT,
            personality={"style": "config_oriented", "communication": "flexibility"},
            capabilities=["config_dev", "dynamic_config", "feature_flags"],
            skills=["config_management", "feature_flags", "dynamic_config"],
            tools=["config_manager", "feature_flag", "dynamic_config"],
            system_prompt="You are a configuration development engineer."),
    ]
    for agent in agents:
        registry.register(agent)
    return agents


def create_ps_agents(registry: AgentRegistry) -> List[AgentProfile]:
    """Create 8 Project Support agents"""
    agents = [
        AgentProfile(agent_id="ps_001", name="Zhang Tech Support", agent_type=AgentType.PROJECT_SUPPORT,
            personality={"style": "tech_support", "communication": "problem_solving"},
            capabilities=["tech_support", "problem_diagnosis", "solution_provision"],
            skills=["problem_diagnosis", "tech_support", "solution_design"],
            tools=["support_kit", "diagnostic_tools", "solution_designer"],
            system_prompt="You are a technical support expert."),
        AgentProfile(agent_id="ps_002", name="Li Ops Support", agent_type=AgentType.PROJECT_SUPPORT,
            personality={"style": "ops_oriented", "communication": "stability"},
            capabilities=["ops_support", "monitoring_alerts", "incident_handling"],
            skills=["ops_monitoring", "alert_handling", "incident_recovery"],
            tools=["monitoring", "alert_manager", "incident_handler"],
            system_prompt="You are an operations support expert."),
        AgentProfile(agent_id="ps_003", name="Wang Documentation Support", agent_type=AgentType.PROJECT_SUPPORT,
            personality={"style": "documentation_professional", "communication": "knowledge_transfer"},
            capabilities=["doc_support", "doc_writing", "knowledge_base_building"],
            skills=["technical_documentation", "user_manual", "knowledge_base"],
            tools=["doc_writer", "knowledge_base", "markdown_tools"],
            system_prompt="You are a documentation support expert."),
        AgentProfile(agent_id="ps_004", name="Liu Training Support", agent_type=AgentType.PROJECT_SUPPORT,
            personality={"style": "training_oriented", "communication": "knowledge_sharing"},
            capabilities=["training_support", "training_material", "training_implementation"],
            skills=["training_design", "material_creation", "training_implementation"],
            tools=["training_kit", "material_designer", "training_platform"],
            system_prompt="You are a training support expert."),
        AgentProfile(agent_id="ps_005", name="Chen Knowledge Manager", agent_type=AgentType.PROJECT_SUPPORT,
            personality={"style": "knowledge_precipitation", "communication": "knowledge_organization"},
            capabilities=["knowledge_management", "experience_precipitation", "best_practices"],
            skills=["knowledge_base_building", "experience_summary", "best_practices"],
            tools=["knowledge_manager", "wiki", "best_practice_db"],
            system_prompt="You are a knowledge management expert."),
        AgentProfile(agent_id="ps_006", name="Yang Process Support", agent_type=AgentType.PROJECT_SUPPORT,
            personality={"style": "process_optimization", "communication": "efficiency_improvement"},
            capabilities=["process_support", "process_optimization", "efficiency_improvement"],
            skills=["process_analysis", "process_optimization", "efficiency_tools"],
            tools=["process_tools", "efficiency_analyzer", "automation_kit"],
            system_prompt="You are a process support expert."),
        AgentProfile(agent_id="ps_007", name="Zhao Data Support", agent_type=AgentType.PROJECT_SUPPORT,
            personality={"style": "data_oriented", "communication": "data_accuracy"},
            capabilities=["data_support", "data_organization", "data_validation"],
            skills=["data_organization", "data_validation", "data_cleaning"],
            tools=["data_tools", "validator", "cleaner"],
            system_prompt="You are a data support expert."),
        AgentProfile(agent_id="ps_008", name="Sun Environment Support", agent_type=AgentType.PROJECT_SUPPORT,
            personality={"style": "environment_stability", "communication": "quick_response"},
            capabilities=["environment_support", "environment_config", "environment_monitoring"],
            skills=["environment_config", "environment_monitoring", "environment_recovery"],
            tools=["env_manager", "config_center", "health_checker"],
            system_prompt="You are an environment support expert."),
    ]
    for agent in agents:
        registry.register(agent)
    return agents


def create_engineering_agents(registry: AgentRegistry) -> List[AgentProfile]:
    """Create 12 Engineering agents"""
    agents = [
        AgentProfile(agent_id="eng_001", name="Zhang Architecture Designer", agent_type=AgentType.ENGINEERING,
            personality={"style": "architecture_minded", "communication": "technical_decision"},
            capabilities=["architecture_design", "technology_selection", "architecture_review"],
            skills=["system_architecture", "microservices", "distributed_design"],
            tools=["architecture_tool", "design_patterns", "modeling"],
            system_prompt="You are an architecture design expert."),
        AgentProfile(agent_id="eng_002", name="Li Infrastructure", agent_type=AgentType.ENGINEERING,
            personality={"style": "infrastructure", "communication": "stability"},
            capabilities=["infrastructure", "cloud_architecture", "resource_management"],
            skills=["cloud_computing", "infrastructure", "resource_planning"],
            tools=["cloud_platform", "infrastructure_as_code", "resource_manager"],
            system_prompt="You are an infrastructure expert."),
        AgentProfile(agent_id="eng_003", name="Wang Security Engineering", agent_type=AgentType.ENGINEERING,
            personality={"style": "security_oriented", "communication": "risk_awareness"},
            capabilities=["security_engineering", "security_architecture", "penetration_testing"],
            skills=["security_architecture", "penetration_testing", "security_hardening"],
            tools=["security_tools", "penetration_testing", "security_audit"],
            system_prompt="You are a security engineering expert."),
        AgentProfile(agent_id="eng_004", name="Liu Performance Engineering", agent_type=AgentType.ENGINEERING,
            personality={"style": "performance_oriented", "communication": "optimization_solution"},
            capabilities=["performance_engineering", "performance_optimization", "capacity_planning"],
            skills=["performance_analysis", "performance_optimization", "capacity_evaluation"],
            tools=["performance_tools", "profiler", "load_tester"],
            system_prompt="You are a performance engineering expert."),
        AgentProfile(agent_id="eng_005", name="Chen Data Engineering", agent_type=AgentType.ENGINEERING,
            personality={"style": "data_architecture", "communication": "data_governance"},
            capabilities=["data_engineering", "data_architecture", "data_governance"],
            skills=["data_modeling", "data_governance", "data_platform"],
            tools=["data_modeling", "data_governance", "data_platform"],
            system_prompt="You are a data engineering expert."),
        AgentProfile(agent_id="eng_006", name="Yang Automation Engineering", agent_type=AgentType.ENGINEERING,
            personality={"style": "automation_minded", "communication": "efficiency_improvement"},
            capabilities=["automation_engineering", "ci_cd", "automated_ops"],
            skills=["ci_cd", "automated_ops", "script_development"],
            tools=["ci_cd_pipeline", "automation_scripts", "orchestration"],
            system_prompt="You are an automation engineering expert."),
        AgentProfile(agent_id="eng_007", name="Zhao Test Engineering", agent_type=AgentType.ENGINEERING,
            personality={"style": "quality_oriented", "communication": "test_strategy"},
            capabilities=["test_engineering", "test_architecture", "quality_assurance"],
            skills=["test_design", "test_framework", "quality_assessment"],
            tools=["test_framework", "test_automation", "quality_metrics"],
            system_prompt="You are a test engineering expert."),
        AgentProfile(agent_id="eng_008", name="Sun Monitoring Engineering", agent_type=AgentType.ENGINEERING,
            personality={"style": "observability", "communication": "alert_response"},
            capabilities=["monitoring_engineering", "logging_system", "trace_tracking"],
            skills=["monitoring_system", "log_analysis", "trace_tracking"],
            tools=["monitoring_stack", "logging_system", "tracing"],
            system_prompt="You are a monitoring engineering expert."),
        AgentProfile(agent_id="eng_009", name="Zhou Disaster Recovery Engineering", agent_type=AgentType.ENGINEERING,
            personality={"style": "high_availability", "communication": "dr_awareness"},
            capabilities=["dr_engineering", "high_availability", "dr_solution"],
            skills=["dr_design", "ha_architecture", "dr_drill"],
            tools=["ha_architecture", "dr_solution", "failover_system"],
            system_prompt="You are a disaster recovery engineering expert."),
        AgentProfile(agent_id="eng_010", name="Wu Network Engineering", agent_type=AgentType.ENGINEERING,
            personality={"style": "network_architecture", "communication": "connection_stability"},
            capabilities=["network_engineering", "network_architecture", "network_security"],
            skills=["network_architecture", "network_security", "load_balancing"],
            tools=["network_tools", "firewall", "load_balancer"],
            system_prompt="You are a network engineering expert."),
        AgentProfile(agent_id="eng_011", name="Zheng Storage Engineering", agent_type=AgentType.ENGINEERING,
            personality={"style": "storage_optimization", "communication": "data_reliability"},
            capabilities=["storage_engineering", "storage_optimization", "data_backup"],
            skills=["storage_architecture", "storage_optimization", "data_protection"],
            tools=["storage_system", "backup_solution", "capacity_planner"],
            system_prompt="You are a storage engineering expert."),
        AgentProfile(agent_id="eng_012", name="Feng Platform Engineering", agent_type=AgentType.ENGINEERING,
            personality={"style": "platform_minded", "communication": "developer_experience"},
            capabilities=["platform_engineering", "paas", "developer_platform"],
            skills=["platform_dev", "paas", "developer_tools"],
tools=["paas_platform", "developer_portal", "api_gateway"],
            system_prompt="You are a platform engineering expert."),
    ]
    for agent in agents:
        registry.register(agent)
    return agents


def create_testing_agents(registry: AgentRegistry) -> List[AgentProfile]:
    """Create 10 Testing agents"""
    agents = [
        AgentProfile(agent_id="test_001", name="Zhang Functional Tester", agent_type=AgentType.TESTING,
            personality={"style": "function_oriented", "communication": "defect_description"},
            capabilities=["functional_testing", "test_cases", "defect_reports"],
            skills=["functional_testing", "test_case_design", "defect_tracking"],
            tools=["test_case_manager", "bug_tracker", "testlink"],
            system_prompt="You are a functional test engineer."),
        AgentProfile(agent_id="test_002", name="Li Automation Tester", agent_type=AgentType.TESTING,
            personality={"style": "automation_minded", "communication": "efficiency_improvement"},
            capabilities=["automation_testing", "framework_dev", "script_maintenance"],
            skills=["automation_framework", "script_development", "continuous_integration"],
            tools=["selenium", "appium", "jenkins"],
            system_prompt="You are an automation test engineer."),
        AgentProfile(agent_id="test_003", name="Wang Performance Tester", agent_type=AgentType.TESTING,
            personality={"style": "performance_sensitive", "communication": "performance_report"},
            capabilities=["performance_testing", "stress_testing", "performance_analysis"],
            skills=["performance_testing", "load_testing", "performance_analysis"],
            tools=["jmeter", "loadrunner", "gatling"],
            system_prompt="You are a performance test engineer."),
        AgentProfile(agent_id="test_004", name="Liu Security Tester", agent_type=AgentType.TESTING,
            personality={"style": "security_aware", "communication": "vulnerability_description"},
            capabilities=["security_testing", "penetration_testing", "vulnerability_assessment"],
            skills=["penetration_testing", "vulnerability_scanning", "security_assessment"],
            tools=["owasp", "burp", "nessus"],
            system_prompt="You are a security test engineer."),
        AgentProfile(agent_id="test_005", name="Chen API Tester", agent_type=AgentType.TESTING,
            personality={"style": "api_oriented", "communication": "contract_verification"},
            capabilities=["api_testing", "api_testing", "contract_testing"],
            skills=["api_testing", "api_verification", "contract_testing"],
            tools=["postman", "soapui", "contract_testing"],
            system_prompt="You are an API test engineer."),
        AgentProfile(agent_id="test_006", name="Yang Mobile Tester", agent_type=AgentType.TESTING,
            personality={"style": "mobile_experience", "communication": "compatibility_issues"},
            capabilities=["mobile_testing", "compatibility_testing", "real_device_testing"],
            skills=["mobile_testing", "compatibility_testing", "real_device_debugging"],
            tools=["appium", "testflight", "android_studio"],
            system_prompt="You are a mobile test engineer."),
        AgentProfile(agent_id="test_007", name="Zhao UI Tester", agent_type=AgentType.TESTING,
            personality={"style": "visual_sensitive", "communication": "ui_issues"},
            capabilities=["ui_testing", "visual_testing", "experience_testing"],
            skills=["ui_testing", "visual_verification", "experience_assessment"],
            tools=["visual_testing", "screenshot_comparison", "ux_checking"],
            system_prompt="You are a UI test engineer."),
        AgentProfile(agent_id="test_008", name="Sun Regression Tester", agent_type=AgentType.TESTING,
            personality={"style": "regression_aware", "communication": "version_verification"},
            capabilities=["regression_testing", "version_verification", "quick_feedback"],
            skills=["regression_strategy", "version_testing", "quick_verification"],
            tools=["regression_suite", "smoke_test", "sanity_test"],
            system_prompt="You are a regression test engineer."),
        AgentProfile(agent_id="test_009", name="Zhou UAT Tester", agent_type=AgentType.TESTING,
            personality={"style": "business_oriented", "communication": "customer_perspective"},
            capabilities=["uat_testing", "user_acceptance", "delivery_confirmation"],
            skills=["uat", "acceptance_criteria", "delivery_confirmation"],
            tools=["uat_tools", "acceptance_criteria", "sign_off"],
            system_prompt="You are a UAT test engineer."),
        AgentProfile(agent_id="test_010", name="Wu Test Manager", agent_type=AgentType.TESTING,
            personality={"style": "test_strategy", "communication": "quality_control"},
            capabilities=["test_management", "test_strategy", "quality_assessment"],
            skills=["test_planning", "test_strategy", "quality_management"],
            tools=["test_management", "quality_dashboard", "metrics"],
            system_prompt="You are a test management expert."),
    ]
    for agent in agents:
        registry.register(agent)
    return agents


def create_media_agents(registry: AgentRegistry) -> List[AgentProfile]:
    """Create 8 Media agents"""
    agents = [
        AgentProfile(agent_id="media_001", name="Zhang Video Producer", agent_type=AgentType.MEDIA,
            personality={"style": "visual_narrative", "communication": "creative_expression"},
            capabilities=["video_production", "editing_effects", "post_production"],
            skills=["video_editing", "effects_production", "post_synthesis"],
            tools=["premiere", "after_effects", "final_cut"],
            system_prompt="You are a video production expert."),
        AgentProfile(agent_id="media_002", name="Li Graphic Editor", agent_type=AgentType.MEDIA,
            personality={"style": "content_creation", "communication": "written_expression"},
            capabilities=["graphic_editing", "layout_design", "content_creation"],
            skills=["graphic_editing", "layout_design", "content_writing"],
            tools=["photoshop", "illustrator", "indesign"],
            system_prompt="You are a graphic editing expert."),
        AgentProfile(agent_id="media_003", name="Wang Animation Producer", agent_type=AgentType.MEDIA,
            personality={"style": "animation_creative", "communication": "dynamic_expression"},
            capabilities=["animation_production", "mg_animation", "character_animation"],
            skills=["animation_design", "motion_graphics", "character_animation"],
            tools=["after_effects", "maya", "blender"],
            system_prompt="You are an animation production expert."),
        AgentProfile(agent_id="media_004", name="Liu Photo Video", agent_type=AgentType.MEDIA,
            personality={"style": "visual_capture", "communication": "frame_composition"},
            capabilities=["photo_video", "lighting_design", "frame_composition"],
            skills=["photography", "lighting_setup", "frame_composition"],
            tools=["camera", "lighting_kit", "composition_tool"],
            system_prompt="You are a photography expert."),
        AgentProfile(agent_id="media_005", name="Chen Social Media", agent_type=AgentType.MEDIA,
            personality={"style": "social_minded", "communication": "interaction_planning"},
            capabilities=["social_media", "content_ops", "interaction_planning"],
            skills=["social_ops", "content_planning", "fan_interaction"],
            tools=["social_scheduler", "analytics", "engagement_tool"],
            system_prompt="You are a social media expert."),
        AgentProfile(agent_id="media_006", name="Yang Live Streaming Planner", agent_type=AgentType.MEDIA,
            personality={"style": "real_time_interaction", "communication": "live_adaptation"},
            capabilities=["live_planning", "live_execution", "interaction_design"],
            skills=["live_planning", "live_execution", "interaction_design"],
            tools=["streaming_kit", "obs", "interaction_tools"],
            system_prompt="You are a live streaming planner."),
        AgentProfile(agent_id="media_007", name="Zhao Brand Communication", agent_type=AgentType.MEDIA,
            personality={"style": "brand_minded", "communication": "communication_strategy"},
            capabilities=["brand_communication", "pr_planning", "media_relations"],
            skills=["brand_communication", "pr_planning", "media_cooperation"],
            tools=["pr_tools", "media_kit", "communication_analysis"],
            system_prompt="You are a brand communication expert."),
        AgentProfile(agent_id="media_008", name="Sun Multimedia Integration", agent_type=AgentType.MEDIA,
            personality={"style": "integration_minded", "communication": "cross_media_collab"},
            capabilities=["multimedia_integration", "cross_media", "content_matrix"],
            skills=["multimedia_planning", "cross_platform", "content_matrix"],
            tools=["multimedia_kit", "cross_platform", "content_matrix"],
            system_prompt="You are a multimedia integration expert."),
    ]
    for agent in agents:
        registry.register(agent)
    return agents


def create_support_agents(registry: AgentRegistry) -> List[AgentProfile]:
    """Create 6 Support agents"""
    agents = [
        AgentProfile(agent_id="sup_001", name="Zhang Customer Service", agent_type=AgentType.SUPPORT,
            personality={"style": "service_oriented", "communication": "patient_meticulous"},
            capabilities=["customer_service", "problem_answering", "satisfaction_improvement"],
            skills=["customer_service", "problem_handling", "customer_communication"],
            tools=["crm_system", "ticket_system", "knowledge_base"],
            system_prompt="You are a customer service expert."),
        AgentProfile(agent_id="sup_002", name="Li Tech Support", agent_type=AgentType.SUPPORT,
            personality={"style": "tech_oriented", "communication": "professional_explanation"},
            capabilities=["tech_support", "fault_diagnosis", "tech_guidance"],
            skills=["tech_support", "troubleshooting", "remote_assistance"],
            tools=["remote_support", "diagnostic_kit", "knowledge_base"],
            system_prompt="You are a technical support expert."),
        AgentProfile(agent_id="sup_003", name="Wang Training Instructor", agent_type=AgentType.SUPPORT,
            personality={"style": "teaching_oriented", "communication": "vivid_explanation"},
            capabilities=["training_instructor", "course_design", "training_implementation"],
            skills=["training_design", "course_development", "training_lecturing"],
            tools=["training_kit", "slide_maker", "e_learning"],
            system_prompt="You are a training instructor."),
        AgentProfile(agent_id="sup_004", name="Liu After-sales Support", agent_type=AgentType.SUPPORT,
            personality={"style": "after_sales_care", "communication": "proactive_service"},
            capabilities=["after_sales_support", "customer_follow_up", "satisfaction_follow_up"],
            skills=["after_sales_service", "follow_up_management", "satisfaction_survey"],
            tools=["after_sales_kit", "crm", "survey_tool"],
            system_prompt="You are an after-sales support expert."),
        AgentProfile(agent_id="sup_005", name="Chen Online Service", agent_type=AgentType.SUPPORT,
            personality={"style": "quick_response", "communication": "instant_answering"},
            capabilities=["online_service", "instant_response", "problem_triaging"],
            skills=["online_communication", "problem_classification", "quick_response"],
            tools=["live_chat", "chatbot", "response_templates"],
            system_prompt="You are an online service expert."),
        AgentProfile(agent_id="sup_006", name="Yang Community Support", agent_type=AgentType.SUPPORT,
            personality={"style": "community_building", "communication": "active_atmosphere"},
            capabilities=["community_support", "problem_collection", "community_ops"],
            skills=["community_management", "problem_collection", "activity_planning"],
            tools=["forum_kit", "community_tools", "feedback_system"],
            system_prompt="You are a community support expert."),
    ]
    for agent in agents:
        registry.register(agent)
    return agents


def create_sales_agents(registry: AgentRegistry) -> List[AgentProfile]:
    """Create 6 Sales agents"""
    agents = [
        AgentProfile(agent_id="sales_001", name="Zhang Requirement Mining", agent_type=AgentType.SALES,
            personality={"style": "requirement_oriented", "communication": "deep_listening"},
capabilities=["requirement_mining", "opportunity_identification", "customer_visit"],
            skills=["requirement_analysis", "opportunity_discovery", "customer_communication"],
            tools=["crm", "lead_tracker", "meeting_notes"],
            system_prompt="You are a sales expert."),
        AgentProfile(agent_id="sales_002", name="Li Solution Design", agent_type=AgentType.SALES,
            personality={"style": "solution_oriented", "communication": "professional_presentation"},
            capabilities=["solution_design", "product_demo", "technical_exchange"],
            skills=["proposal_writing", "product_demo", "technical_presentation"],
            tools=["proposal_designer", "demo_kit", "presentation"],
            system_prompt="You are a solution design expert."),
        AgentProfile(agent_id="sales_003", name="Wang Business Negotiation", agent_type=AgentType.SALES,
            personality={"style": "business_sensitive", "communication": "negotiation_skills"},
            capabilities=["business_negotiation", "contract_signing", "pricing_strategy"],
            skills=["business_negotiation", "contract_management", "pricing_strategy"],
            tools=["negotiation_kit", "contract_template", "pricing_tool"],
            system_prompt="You are a business negotiation expert."),
        AgentProfile(agent_id="sales_004", name="Liu Customer Management", agent_type=AgentType.SALES,
            personality={"style": "relationship_maintenance", "communication": "long_term_cooperation"},
            capabilities=["customer_management", "relationship_maintenance", "repeat_purchase_improvement"],
            skills=["customer_relationship", "relationship_maintenance", "secondary_sales"],
            tools=["crm", "relationship_tracker", "loyalty_program"],
            system_prompt="You are a customer management expert."),
        AgentProfile(agent_id="sales_005", name="Chen Bid Management", agent_type=AgentType.SALES,
            personality={"style": "bid_expert", "communication": "proposal_creation"},
            capabilities=["bid_management", "proposal_creation", "bidding_strategy"],
            skills=["bid_management", "proposal_writing", "bidding_strategy"],
            tools=["bid_manager", "proposal_writer", "bid_strategist"],
            system_prompt="You are a bid management expert."),
        AgentProfile(agent_id="sales_006", name="Yang Data Analyst", agent_type=AgentType.SALES,
            personality={"style": "data_driven", "communication": "sales_analysis"},
            capabilities=["sales_analysis", "data_analysis", "forecast_report"],
            skills=["sales_analysis", "data_mining", "forecast_modeling"],
            tools=["sales_analyst", "data_miner", "forecast_expert"],
            system_prompt="You are a sales data analysis expert."),
    ]
    for agent in agents:
        registry.register(agent)
    return agents


def create_all_agents_company(registry: AgentRegistry) -> List[AgentProfile]:
    """Create all 130 agents for Agents Company"""
    all_agents = []
    all_agents.extend(create_operations_agents(registry))   # 12
    all_agents.extend(create_design_agents(registry))      # 15
    all_agents.extend(create_product_agents(registry))     # 10
    all_agents.extend(create_rd_agents(registry))          # 20
    all_agents.extend(create_pm_agents(registry))          # 8
    all_agents.extend(create_pjd_agents(registry))          # 15
    all_agents.extend(create_ps_agents(registry))           # 8
    all_agents.extend(create_engineering_agents(registry))  # 12
    all_agents.extend(create_testing_agents(registry))      # 10
    all_agents.extend(create_media_agents(registry))        # 8
    all_agents.extend(create_support_agents(registry))      # 6
    all_agents.extend(create_sales_agents(registry))       # 6
    # Total: 12+15+10+20+8+15+8+12+10+8+6+6 = 130
    logger.info(f"Agents Company created with {len(all_agents)} agents")
    return all_agents


def initialize_agents_company() -> AgentRegistry:
    """Initialize Agents Company"""
    registry = get_agent_registry()
    agents = create_all_agents_company(registry)
    
    print(f"\n{'='*60}")
    print(f"Agents Company initialized")
    print(f"Total agents: {len(agents)}")
    print(f"{'='*60}\n")
    
    return registry


# Global variable for Agents Company
AGENTS_COMPANY: Dict[str, List[AgentProfile]] = {
    "OPERATIONS": [],
    "DESIGN": [],
    "PRODUCT": [],
    "RND": [],
    "PM": [],
    "PJD": [],
    "PS": [],
    "ENGINEERING": [],
    "TESTING": [],
    "MEDIA": [],
    "SUPPORT": [],
    "SALES": [],
}
"""Agents Company 130 agents organized by department"""


def _populate_agents_company():
    """Populate AGENTS_COMPANY dict"""
    if not AGENTS_COMPANY["OPERATIONS"]:
        registry = get_agent_registry()
        agents = create_all_agents_company(registry)
        for agent in agents:
            dept = agent.agent_id.split("_")[0].upper()
            dept_map = {
                "OPS": "OPERATIONS", "DES": "DESIGN", "PROD": "PRODUCT",
                "RD": "RND", "PM": "PM", "PJD": "PJD", "PS": "PS",
                "ENG": "ENGINEERING", "TEST": "TESTING", "MEDIA": "MEDIA",
                "SUP": "SUPPORT", "SALES": "SALES"
            }
            key = dept_map.get(dept, dept)
            if key in AGENTS_COMPANY:
                AGENTS_COMPANY[key].append(agent)


_populate_agents_company()
